### ISSUE TITLE
Stream not closed for {:as :byte-array} in 0.7.4+ ?

### ISSUE THREAD

**Issue by sunng87** [dakrone/clj-http#148]
We are using clj-http in our RSS crawler. And this morning when I upgraded 0.7.5 we got lots of `Too many open files` and `UnknowHostException`. From our experience, I think it's caused by some sorts of file op leaks.

And after I downgraded to 0.7.3, which is before the stream refactoring, the system works OK till now. 

I remember in 0.6.x of clj-http, if we coerce output as :stream, we have to close the stream manually. So to avoid this, we coerce it to :byte-array. And the system works fine with 0.6.x. I'm not clear if the byte-array method also requires manual management on underlying stream.

I will look into the code to see if I can help/.

**Comment by dakrone** [comment]
Closing this since I haven't heard anything in a while, feel free to re-open.
