### ISSUE TITLE
Switch to PoolingHttpClientConnectionManager 

### ISSUE THREAD

**Issue by MarcoPolo** [dakrone/clj-http#170]
In conn-mgr you're using PoolingClientConnectionManager which was deprecated in 4.2.  We should update to PoolingHttpClientConnectionManager to make SOCKS proxy possible. (#169)

**Comment by clyfe** [comment]
I master c9d1cb104ce9b67e8c4e7e4245c40c38b5eda13c

```clojure
(require '[clj-http.client :as client]
         '[clj-http.conn-mgr :as cm]) 
(client/request {:handler println 
                 :method :get 
                 :url    "http://www.google.com" 
                 :connection-manager (cm/make-reusable-conn-manager {:default-per-route 10})})

; => java.lang.ClassCastException: 
;     org.apache.http.impl.conn.PoolingClientConnectionManager cannot be cast to 
;     org.apache.http.conn.HttpClientConnectionManager
```

**Comment by dakrone** [comment]
@clyfe Yeah :( master is in flux while I try to iron out all the build failures and transition from deprecated -> non-deprecated, any help is appreciated :)

**Comment by dskrvk** [comment]
Related to https://github.com/dakrone/clj-http/issues/247.

**Comment by dakrone** [comment]
This has been complete for a while now, so closing this.
