### ISSUE TITLE
Custom SSLContext?

### ISSUE THREAD

**Issue by dparoulek** [dakrone/clj-http#174]
I'm currently using httpclient to connect to sites that require authentication using certificates from a smart card reader. This involves creating a keystore from the card reader and using a custom sslcontext similar to this example: http://hc.apache.org/httpcomponents-client-4.3.x/httpclient/examples/org/apache/http/examples/client/ClientCustomSSL.java

I'd love to use clj-http. I started looking thru the code and looks like I could switch the DefaultHttpClient in core/request with a custom ClosableHttpClient that references the custom SSLContext. 

Updating the request method and using should work for this one time. But just curious if there's a better way to use a custom SSLContext? If not, would that be something that other people might need? And if so, I could maybe take a stab at sending a pull request. I'm pretty new to the ssl, httpclient, etc java libs so might be more than I can tackle at the moment, but could give it shot if other's might find it useful. 

Thanks, 
Dave

**Comment by dakrone** [comment]
@arbelt are you still having this issue? Also, SSLv3 is considered dangerous and should not be used.

**Comment by dakrone** [comment]
Closing as there has been no feedback and I believe this has been resolved, feel free to comment if this was closed erroneously.
