### ISSUE TITLE
Output http request as text

### ISSUE THREAD

**Issue by Lepetere** [dakrone/clj-http#185]
Is there any way to output the http request built by clj-http as pure text?
I have the problem that I have to build a rather complicated multipart request and to do it I really need to see the actual text that is put together by clj-http. Otherwise I don't know how to use the parameters I can pass to the :multipart option right.

**Comment by skilbjo** [comment]
@rfn01  thank you! That's a brilliant idea, and helped me debug the request to the API I was working with!
