### ISSUE TITLE
Multipart Message Boundary String

### ISSUE THREAD

**Issue by Lepetere** [dakrone/clj-http#191]
Me and multipart requests again...

I need to generate a multipart request with the following header:

```
content-type: multipart/form-data; boundary=XXXsubpartXXX
```

So this means I need to tell the server already in the header which boundary string will be used in the body.

Since clj-http generates boundary strings automatically, is there any way to get this boundary string before the http message is sent, so I can add it to the header?

The other way of dealing with this would be for me to specify a boundary string myself. Is that possible?

Btw I found this: https://groups.google.com/forum/#!topic/clojure/JGCKVAqP6h4
But it didn't really help me since I don't really want to generate the body myself.

**Comment by dakrone** [comment]
Closing as there has been no progress on this in four years, the linked message contains a workaround. If anyone else would like this or disagrees let me know and I'll be happy to re-open it.
