### ISSUE TITLE
(:headers request) is not a clojure.lang.IObj

### ISSUE THREAD

**Issue by nscott** [dakrone/clj-http#193]
I'm not entirely sure if this is truly a problem, but it's definitely something I ran into.
See https://github.com/marick/Midje/issues/266 for all the gory details at the bottom of my comment.

Essentially it looks like potemkin (or clj-http changing something potemkin gives) does not actually implement clojure.lang.IObj. This will make midje consistently fail unless the clj-http.headers/wrap-header-map middleware is excluded.

In general, I think it's reasonable to see that a map is extending IObj; the default maps do.

Evaluate `(isa? (type (:headers (client/get "http://example.com"))) clojure.lang.IObj)` and you'll see that indeed, it is not an IObj.

`(isa? (type {}) clojure.lang.IObj)` evaluates to true, and `(bases (type {}))` explicitly mentions clojure.lang.IObj.

Anyway, I'm not sure if this is a clj-http problem or a potemkin problem. Just wanted to bring it to your attention.

**Comment by atroche** [comment]
The potemkin PR  merged, btw. Does that mean this issue can be closed?

**Comment by dakrone** [comment]
@atroche yep, this has been fixed, thanks!
