### ISSUE TITLE
Import and export cookies

### ISSUE THREAD

**Issue by adamzy** [dakrone/clj-http#194]
Hi, 
I want to save cookies from cookie-store to files for later use, or pass them to another cookie-store.  I am not familiar with Clojure, but the following code will do.

``` clojure
;; in cookie.clj
(defn get-client-cookies
  [cookie-store]
  (seq (.getCookies cookie-store)))

(defn add-client-cookies
  [cookie-store client-cookies]
  (dorun
   (map #(.addCookie cookie-store %)
        (if (sequential? client-cookies)
          client-cookies
          [client-cookies])))
  cookie-store)
```

Then we can use

``` clojure
(add-client-cookies a-cookie-store (get-client-cookies another-cookie-store))
```

Hope this feature can be added in later releases.

**Comment by dakrone** [comment]
Closing this as it is very old and we already have an `add-cookie` method
