### ISSUE TITLE
Full HTTP response string

### ISSUE THREAD

**Issue by ath** [dakrone/clj-http#196]
For debugging there is the option `:debug true` which returns a map. This is useful, but even more helpful it would be to see the complete response string, including headers, as if a packet sniffer recorded the whole thing.

**Comment by itegebo** [comment]
👍   I was surprised this wasn't already the case, and further surprised that no one has added (or documented) logging support.

**Comment by dakrone** [comment]
I agree with this. I've started working on a way to do this.

**Comment by dakrone** [comment]
I've pushed the beginning of this in https://github.com/dakrone/clj-http/pull/440
