### ISSUE TITLE
get fails on a nginx server with two certificates, two domains.

### ISSUE THREAD

**Issue by rishikulkarni** [dakrone/clj-http#202]
1. (:require '[clj-http.client :as client])
2. (client/get "https://oneklikstreet.com/api/v1/?format=json")

SSLException hostname in certificate didn't match: <oneklikstreet.com> != <1click.io> OR <1click.io> OR <www.1click.io >  org.apache.http.conn.ssl.AbstractVerifier.verify (AbstractVerifier.java:231)
1. (client/get "https://1click.io/api/v1/?format=json")
   works.
2. curl works on both the links. I have an ssl certificate on oneklikstreet.com and on 1click.io. Both domains point to same IP and running on same nginx.
3. I tried http-kit which seems to work.

**Comment by shaunlebron** [comment]
same problem with Github API here:

```
clojure.lang.Compiler$CompilerException: javax.net.ssl.SSLException: hostname in certificate didn't match: <uploads.github.com> != <*.githubusercontent.com> OR <*.githubusercontent.com> OR <githubus
ercontent.com>, compiling:(/Users/swilliam/code/cljsinfo/api-docs/travis/publish.clj:51:53)
```

**Comment by wilb** [comment]
Has there been any further progress on the development of this?

**Comment by terjesb** [comment]
I'm also running into this issue, against Nginx utilizing SNI certificates.

**Comment by sgerrand** [comment]
I've also encountered this issue, setup exactly the same as @terjesb described above. :pouting_cat:

**Comment by lookfirst** [comment]
I'm a circleci user. circleci uses this lib for their [notification mechanism](https://circleci.com/docs/configuration#notify). I've got a bot sitting on a port behind the free tier cloudflare ssl, which uses SNI. Things are broken for me. :cry: :smile:

**Comment by dakrone** [comment]
Okay, I have progressed with this.

I've branched old master to become the `2.x` branch (for stable releases). I've also bumped master to 3.0.0-SNAPSHOT and merged the work I started rewriting clj-http to use the new apache http interfaces (non deprecated ones).

I just tested this with https://uploads.github.com and it works (where 2.0.0 doesn't) due to the SNI certificate.

The work isn't done on master and a lot of tests still fail because I haven't added support for them, but the 3.0.0 will be based on master and thus have this fix.

In the meantime, if anyone can test the master branch against URLs that previously failed and let me know whether it is fixed, that would be very appreciated! (patches fixing tests also appreciated!)

/cc @Frozenlock @lookfirst @terjesb @sgerrand @shaunlebron @wilb @wilkerlucio @llasram

**Comment by giricme** [comment]
@dakrone I had the same issue with 2.0.0. I built the latest from master and my SSL handshake errors are now gone. Thanks.

**Comment by lopusz** [comment]
@dakrone Similar with me. For site tested by me branch 2.x throws exception, but master works fine.

Great to see a progress on this issue! Thank you!

**Comment by dakrone** [comment]
Great! I have cleaned up the branch so all the unit tests pass, though there are still 8 integration tests that fail (because basically it's a rewrite of `core.clj`). Once I get those passing I'll do a release.

**Comment by jackrusher** [comment]
@dakrone Any chance of a SNAPSHOT build of Clojars in the meantime? I'd rather use clj-http, but without SNI I can't (AWS API Gateway needs it, sadly). Thanks in advance!

**Comment by jplaza** [comment]
3.0.0-SNAPSHOT working for me too against AWS API Gateway
Thanks! :smile:

**Comment by swam92** [comment]
@jackrusher I get the same error trying to hit AWS API Gateway.  How did you fix this?

**Comment by jackrusher** [comment]
@swam92 Did you update to 3.0.0-SNAPSHOT?

**Comment by swam92** [comment]
@jackrusher Yes, I am running it against AWS API Gateway.  A get works for https://google.com, but not for https://my-api-gateway-domain.com.  Its a handshake failure and the message in the REPL is:
SSLHandshakeException Received fatal alert: handshake_failure  sun.security.ssl.Alerts.getSSLException (Alerts.java:192)

**Comment by kenrestivo** [comment]
Interestingly, a few years have passed and I'm still having this problem with clj-http 2.0.0

client/get to an HTTPS server with two certificates "redmatrix.nl" and "hubzilla.nl"  fails consistently with clj-http. 

The problem can be seen with
```sh
openssl s_client -showcerts -connect redmatrix.nl:443
```
The server by default serves up the certificate for hubzilla.nl when it's not given any SNI parameters.

Did SNI support ever land in clj-http? Is there some flag to enable it that I missed in the documentation?

**Comment by jvah** [comment]
I'm also a bit puzzled what is the status of this, I need SNI support and would prefer to use clj-http...

**Comment by jplaza** [comment]
@jvah I'm using 3.0.0-SNAPSHOT and that's working for me now.
@dakrone considering releasing 3.0 as Christmas present? Haha :)

**Comment by dakrone** [comment]
@jplaza haha, there's still a lot of things that need to be fixed before 3.0 can be released, so any help is welcome :)

**Comment by technomancy** [comment]
This is fixed now, right?

**Comment by dakrone** [comment]
This  should be fixed now that SNI is supported in the 3.x versions, I'll close this.
