### ISSUE TITLE
Provide a way to get the complete original headers including set-cookie fields

### ISSUE THREAD

**Issue by exi** [dakrone/clj-http#209]
Hi, i am trying to write a kind of http-proxy that forwards requests to another host.
To do this properly, i need access to the raw set-cookie header fields so i don't have to reencode/recreate them for the response to the proxy client. It would be great to have a way to not dissoc the 'set-cookie' header field in cookies.clj:91 to have access to the real headers.

**Comment by dakrone** [comment]
Closing as there has been no feedback, feel free to comment if this was closed erroneously.
