### ISSUE TITLE
Turning off org.apache.http logging?

### ISSUE THREAD

**Issue by locopati** [dakrone/clj-http#22]
When I run code using clj-http in the repl, I'm seeing a ton of logging messges like...
DEBUG            pool-1-thread-18 20111109 095547,513 org.apache.http.impl.conn.SingleClientConnManager ] Releasing connection org.apache.http.impl.conn.SingleClientConnManager$ConnAdapter@4ea6c971
DEBUG            pool-1-thread-18 20111109 095547,513 org.apache.http.impl.conn.SingleClientConnManager ] Released connection open but not reusable.
DEBUG            pool-1-thread-18 20111109 095547,513 org.apache.http.impl.conn.DefaultClientConnection ] Connection shut down

I haven't passed in any options that would turn these on - only using :throw-exceptions false
How can I turn these off?

**Comment by mantree** [comment]
This recently started irritating me when running some integration tests from the repl. To take back control I ended up with the following:

Using Timbre, adding the following deps to get the http client log into timbre:
                 [com.fzakaria/slf4j-timbre "0.3.7"]
                 [org.slf4j/log4j-over-slf4j "1.7.25"]

Then setting the level in the test namespace:

(timbre/set-level! :warn)

**Comment by LouDnl** [comment]
> This recently started irritating me when running some integration tests from the repl. To take back control I ended up with the following:
> 
> Using Timbre, adding the following deps to get the http client log into timbre: [com.fzakaria/slf4j-timbre "0.3.7"] [org.slf4j/log4j-over-slf4j "1.7.25"]
> 
> Then setting the level in the test namespace:
> 
> (timbre/set-level! :warn)

This made my day, even 5 years after. Finally able to see  logs from the backend
