### ISSUE TITLE
net::ERR_INVALID_CHUNKED_ENCODING 

### ISSUE THREAD

**Issue by tomgeorge** [dakrone/clj-http#226]
Hi,

I have a cljs/compojure app that uses cljs-http to send GET/POSTs to the compojure backend.  The compojure routes use clj-http to send GET/POSTs to a spring REST web service.  When I try to hit the endpoint via the redirect url, I get:

```
Resource interpreted as Document but transferred with MIME type application/json:     "http://www.my.url.com/request"
GET http://www.my.url.com/request net::ERR_INVALID_CHUNKED_ENCODING 
```

in the console.

Has anyone seen an issue like this before?

I think that the response from Spring is coming back chunked (or maybe it's clj-http, in the source it says if you don't supply a length it defaults to -1 and chunked transfer)...  Is there a way I can let clj-http/cljs-http know that the response is chunked?

EDIT:  I should say I've been developing this using lein-ring with a jetty dev server.  I deployed a war to Tomcat 7, where I first encountered this issue.

EDIT 2: I can see the response come back from the clj-http/GET in compojure fine.  It appears that going from server -> client is the issue, which makes me suspect cljs-http?  I guess this can be closed.

**Comment by edmondkong** [comment]
Hi, 

Did you manage to resolve this in the end?

I am currently running into the exact same issue. I am trying to proxy requests to http://127.0.0.1:3000 (Grafana service) through my Clojure application at the path http://127.0.0.1/grafana. When I try to access this path through the browser, it gives me the ERR_INVALID_CHUNKED_ENCODING error.

I'm aware that this is an old issue but perhaps you could help me if you remember. 

Thanks.
