### ISSUE TITLE
Deprecated org.apache.http dependencies

### ISSUE THREAD

**Issue by atroche** [dakrone/clj-http#247]
We use a number of [deprecated HttpComponents packages](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/deprecated-list.html), including:
-    `org.apache.http.client.params`
-    `org.apache.http.conn.params`
-    `org.apache.http.cookie.params`
-    `org.apache.http.conn.scheme`

Might be a good idea to use the new APIs?

**Comment by dakrone** [comment]
I have intended to do this for a while. I started a rewrite of `core.clj` on the `apache-4.3-rewrite` branch, but of course all of the ways to construct clients are different, so it has been taking a while! :)

**Comment by dakrone** [comment]
If you are interested in helping with the 4.3 API migration, I would be more than happy to give you commit rights :)

**Comment by dakrone** [comment]
I branched master to 2.x and merged changes to the new master that started to address this, still a WIP.

**Comment by atroche** [comment]
looking great so far!

**Comment by dakrone** [comment]
I believe this can be closed now with 3.x and master branches.
