### ISSUE TITLE
java.lang.NoSuchFieldError: DEF_CONTENT_CHARSET

### ISSUE THREAD

**Issue by hellofunk** [dakrone/clj-http#249]
I have a project started several months ago when the version was `[clj-http "0.7.7"]`.  I'm happy to upgrade but first I want to make sure this issue isn't something else. The app has worked fine for several months, just in the last few days I get a stacktrace that starts at the top with this:

```
java.lang.NoSuchFieldError: DEF_CONTENT_CHARSET 
	at org.apache.http.impl.client.DefaultHttpClient.setDefaultHttpParams(DefaultHttpClient.java:175)
	at org.apache.http.impl.client.DefaultHttpClient.createHttpParams(DefaultHttpClient.java:158)
	at org.apache.http.impl.client.AbstractHttpClient.getParams(AbstractHttpClient.java:448)
	at clj_http.core$set_client_param.invoke(core.clj:53)
	at clj_http.core$add_client_params_BANG_.invoke(core.clj:123)
	at clj_http.core$request.invoke(core.clj:229)
	at clojure.lang.Var.invoke(Var.java:379)
	at clj_http.client$wrap_request_timing$fn__12458.invoke(client.clj:651)
	at clj_http.client$wrap_lower_case_headers$fn__12455.invoke(client.clj:642)
	at clj_http.client$wrap_query_params$fn__12394.invoke(client.clj:520)
```

Why would this suddenly start happening, when no server code has changed, none of the code I'm using that interacts with the server in any way has been updated in a while. Is there some sort of upstream issue that is trickling down? If I haven't changed any dependencies in my app at all, what would lead to this suddenly?

**Comment by dakrone** [comment]
Hmm.. can you send me the output of `lein deps :tree` from your project? Perhaps another dependency is using a different version of apache http

**Comment by hellofunk** [comment]
Your response was enough for me to get it working. I ran `lein deps :tree` and saw this up top:

```
Possibly confusing dependencies found:
[org.clojure/data.json "0.2.4"]
 overrides
[refactor-nrepl "0.3.0-SNAPSHOT"] -> [org.clojure/data.json "0.2.5"]

Consider using these exclusions:
[refactor-nrepl "0.3.0-20150109.063723-14" :exclusions [org.clojure/data.json]]

[cider/cider-nrepl "0.8.2"] -> [org.clojure/java.classpath "0.2.0" :exclusions [org.clojure/clojure]]
 overrides
[ring/ring-devel "1.2.2"] -> [ns-tracker "0.2.2"] -> [org.clojure/java.classpath "0.2.2"]

Consider using these exclusions:
[ring/ring-devel "1.2.2" :exclusions [org.clojure/java.classpath]]

[ring/ring-codec "1.0.0"] -> [commons-codec "1.6"]
 overrides
[clj-http "0.7.7"] -> [commons-codec "1.8"]

Consider using these exclusions:
[clj-http "0.7.7" :exclusions [commons-codec]]

```

While I did not make any changes to the code base recently, I did recently upgrade to latest version of `cider` for emacs and also added in `refactor-nrepl` in my `.lein/profiles.clj` -- As soon as I removed `refactor-nrepl` the error I reported above went away.

This is disappointing. I like the refactor tools and I find it very odd that they cause my app to crash like this.

**Comment by dakrone** [comment]
Closing this for now, feel free to re-open.

**Comment by hellofunk** [comment]
Sorry I should have closed this myself. The problem lay with refactor-clj. It was resolved with some recent updates to that tool.
