### ISSUE TITLE
Client Side Certificates

### ISSUE THREAD

**Issue by creese** [dakrone/clj-http#252]
Do you know if it's possible to make a request using a client side certificate?
https://github.com/request/request#tlsssl-protocol
http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification

**Comment by lvh** [comment]
Inquiring minds would like to know :)

**Comment by dakrone** [comment]
Looks like this is possible from the Apache side (see [this stackoverflow answer](http://stackoverflow.com/questions/21223084/how-to-use-ssl-client-certificate-with-apache-httpclient)), but isn't implemented in clj-http yet.

**Comment by wing328** [comment]
+1

**Comment by xhh** [comment]
:+1:

**Comment by taylorwood** [comment]
I was able to get a client certificate request to work, and I saw what looks like [client certificate request tests](https://github.com/dakrone/clj-http/blob/a565546284351c18acee9533c8ceb34c43d1750c/test/clj_http/test/conn_mgr_test.clj#L66) in the repo. It looks like the necessary steps are happening [here](https://github.com/dakrone/clj-http/blob/a565546284351c18acee9533c8ceb34c43d1750c/src/clj_http/conn_mgr.clj#L88-L103).

There's a very nice [test page](https://slsh.iki.fi/client-certificate/) linked in the SO answer above, and I got a good response using the supplied JKS keystore. I had to locally tweak clj-http to separate passwords for the keystore and certificate, but this shouldn't be an issue if your passwords are the same.

```clojure
(core/request
  {:request-method     :get
   :scheme             :https
   :uri                "slsh.iki.fi/client-certificate/protected/"
   :keystore           "test-resources/clientkeystore.jks"
   :keystore-pass      "keystorepass"})
```

**Comment by dakrone** [comment]
Closing this as I believe it's been implemented with the `:keystore` functionality. If I'm mistaken please let me know and I'll be happy to re-open.
