### ISSUE TITLE
transit-clj "0.8.259" spuriously depends on test.check

### ISSUE THREAD

**Issue by gfredericks** [dakrone/clj-http#256]
The current release of clj-http accidentally includes test.check as a normal dependency via `[transit-clj "0.8.259"]`; this is fixed in [this commit of transit-clj](https://github.com/cognitect/transit-clj/commit/640c35166740642f5c197c78883784acb993d7a1) and I presume also in the latest releases (the latest is `0.8.269` according to the README).

**Comment by dakrone** [comment]
Thanks for opening this!
