### ISSUE TITLE
HTTP 304 (Not Modified) as unexceptional response?

### ISSUE THREAD

**Issue by zsau** [dakrone/clj-http#259]
I'm writing a client that will make a lot of requests with If-Modified-Since headers. It's unfortunate that 304 responses are considered "exceptional" in clj-http, since that forces catching exceptions to handle this normal and expected response.

Would you consider just treating every 2xx and 3xx response as unexceptional?

**Comment by dakrone** [comment]
I think 304 definitely fits for an unexceptional response, I all add it to the list.

I don't want to make all 3xx responses unexceptional because 305 means "use proxy" and the content can't be accessed without a proxy, I think that should be an exception.

**Comment by zsau** [comment]
Thanks!

My thinking about 305s and other similar codes was that they're probably so rare that it's not worth carving out exceptions from the 2xx and 3xx ranges, but you probably know better about that than I do.
