### ISSUE TITLE
 clj-http.headers/HeaderMap breaks under 1.7

### ISSUE THREAD

**Issue by coltnz** [dakrone/clj-http#266]
Long story short it doesn't implement Iterable which is implied by it being a IPersistentMap

user=> (.iterator (headers/header-map :a :b))

AbstractMethodError clj_http.headers.HeaderMap.iterator()Ljava/util/Iterator;  sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)

This is because of http://dev.clojure.org/jira/browse/CLJ-1602, for more details see Alex's second post in https://groups.google.com/forum/m/?fromgroups#!topic/clojure-dev/ccZuKTYKDPc

**Comment by joegallo** [comment]
This seems like a bug in potemkin upstream, so I've submitted a PR there. If it gets merged, then I think we're good to go with just a version bump here.

**Comment by dakrone** [comment]
Should be closed by #274, I'll release a new version for 1.7.0 compatibility very soon.

**Comment by dakrone** [comment]
Released 2.0.0 with a fix for this.
