### ISSUE TITLE
POST throws NoHttpResponseException / CURL works

### ISSUE THREAD

**Issue by priyatam** [dakrone/clj-http#267]
I can post a document to this [server](http://developer.couchbase.com/mobile/develop/references/couchbase-lite/rest-api/document/post---db-/index.html) with curl successfully, like so

    curl -X POST -H 'Content-Type: application/json' -d "{\"json\": \"input\"}" http://id:pwd@localhost:5984/test

The equivalent clj-http api with body or form-params throws the following error 

    (client/post "http://localhost:5984/test" {:basic-auth ["id" "pwd"] :content-type :json :body "{\"json\": \"input\"}"})
    >> NoHttpResponseException localhost:5984 failed to respond     
    org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead 
    (DefaultHttpResponseParser.java:143)

Strangely, this happens only on POST requests that accept a body, and GET, HEAD, PUT, DELETE apis are working. Is this issue related to "stale connections" in http-client v4.4.1 as described [here](https://issues.apache.org/jira/browse/HTTPCLIENT-1610)?

**Comment by priyatam** [comment]
Turns out, I have to use persistent-connections. Sent PR with updated README.

**Comment by venkatperi** [comment]
@priyatam We're seeing this issue interimttently, but aren't using a connection pool, just `http/post` like your example above.

> Turns out, I have to use persistent-connections.

Did you mean that one **always** needs to use a connection pool with `http/post` to avoid these errors?
