### ISSUE TITLE
Request body gets replayed during redirects

### ISSUE THREAD

**Issue by aredington** [dakrone/clj-http#271]
When clj-http client is configured to follow redirects, and posts to a server that responds with a redirect (e.g. an authentication gateway that returns a 303 to an originally requested resource), it preserves all of the entries in the request map that generate a request body, including the :body and :content-type top level keys, and the "content-type" key in the :headers map.

This results in sending get requests with a body, which while not invalid, is often not what is expected of any participants in the HTTP session, particularly with the body that was appropriate to the request that initiated redirecting.

With confirmation that this issue is something that @dakrone  would like resolved, I will open a pull request w/ tests and fix.

**Comment by joegallo** [comment]
Am I correct in understanding that this is primarily about the case of a post-redirects-to-get sort of response? That is, you explicitly don't want to replay the request as it originally was (but at a new url), but instead just follow the redirect via a simple get to the indicated url. Right?

**Comment by aredington** [comment]
@joegallo That's exactly correct. In our particular use case, a POST with a multipart form content body receives a 303 response. The clj-http client follows the redirect in the 303 with a GET request, and provides the same multipart form content body as the content of said GET.

**Comment by joegallo** [comment]
Okay, in that case it seems like it should be pretty straightforward to dissoc the body in [follow-redirect](https://github.com/dakrone/clj-http/blob/0d1a017caf1479c992bee06228f803bc9de73cd7/src/clj_http/client.clj#L200-L217).

I'm trying to come up with a situation where removing the POST body wouldn't make sense. Perhaps it would be a good idea to only remove the body in the case where the original request was a POST?

**Comment by joegallo** [comment]
I'm just thinking that if PRG is ubiquitous enough to get its own [wikipedia page](https://en.wikipedia.org/wiki/Post/Redirect/Get), then it's probably worth supporting more fully. :D

**Comment by aredington** [comment]
I've already resolved this locally with a quick hack by monkey-patching `clj-http.client/follow-redirect` (https://github.com/dakrone/clj-http/blob/master/src/clj_http/client.clj#L200) to dissoc the values in the request I described opening the issue. This seemed consistent with existing principles of follow-redirect's implementation, as it already will dissoc the :query-params key when following the redirect (https://github.com/dakrone/clj-http/blob/master/src/clj_http/client.clj#L213)

I agree that it's a sufficiently impactful change that considering undesired consequences deserves some time, it's not a sufficiently burning issue to demand immediate resolution, and my team has already worked around the issue with a satisfactory temporary fix.

**Comment by dakrone** [comment]
I think this issue is no longer relevant, clj-http has vastly different redirect handling now in the later versions. Since this is a couple of years old, I'm going to close this. If this is still a problem let me know and I'll be more than happy to re-open it.
