### ISSUE TITLE
SSLHandshakeException Received fatal alert: handshake_failure  sun.security.ssl.Alerts.getSSLException 

### ISSUE THREAD

**Issue by kimh** [dakrone/clj-http#275]
I'm using clj-htp 1.1.0 and got this `handshake_failure` error.

```clj
clj-sample.core=> (require '[clj-http.client :as client]) (def url "https://8999uojw48.execute-api.us-east-1.amazonaws.com/prod/webhook")  (client/get url)
nil
#'clj-sample.core/url

SSLHandshakeException Received fatal alert: handshake_failure  sun.security.ssl.Alerts.getSSLException (Alerts.java:192)
```

The site only supports TLS and I'm wondering if this is caused by clj-http not using TLS for some reasons. I understand this must be handled by Apache http client but could it be the case that clj-http doesn't use TLS support?

Please let me know if you need more info. Thank you for your help!

**Comment by jackrusher** [comment]
@kimh There's support for this coming in the 3.0 branch, as mentioned here: https://github.com/dakrone/clj-http/issues/202

**Comment by kimh** [comment]
@jackrusher ok, that sounds good. I can close this issue, but where do I see 3.0 branch?

**Comment by jackrusher** [comment]
@kimh dunno, I've requested that the author/maintainer make a provisional release to clojars, but haven't heard anything yet.

**Comment by dakrone** [comment]
@jackrusher @kimh I've pushed 3.0.0-SNAPSHOT to clojars, it definitely still has rough edges though!

**Comment by kimh** [comment]
I'll close this issue since this is already being discussed in #202

**Comment by jackrusher** [comment]
Thanks, @dakrone!
