### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by martinraison** [dakrone/clj-http#276]
The README indicates that IPv6 is supported, however I'm always getting NoRouteToHostException. I tried with the `client/get` example in the README and tried with multiple IPv6 hosts (including the one in the README). I should note that using curl on the same hosts works without any problem.

**Comment by dakrone** [comment]
Hi @martinraison, can you post how you are trying to issue the request? And do you have a full stacktrace for the exception you're getting?

**Comment by martinraison** [comment]
Thanks for your reply. Actually it looks like it is more an issue with my Java setup, since merely trying to instantiate a java.net.Socket with an IPv6 host was failing.
