### ISSUE TITLE
json coercion doesn't work in version 2.0.0

### ISSUE THREAD

**Issue by sroller** [dakrone/clj-http#281]
the following form returns a map with version 1.1.2 but a JSON string in version 2.0.0

```clojure
(:body (clj-http.client/get "https://coinbase.com/api/v1/prices/spot_rate?currency=CAD" {:as :json}))

**Comment by dakrone** [comment]
@sroller 2.0.0 included a breaking change where optional dependencies are now *not* included by default, see: https://github.com/dakrone/clj-http#optional-dependencies

Does your project include the `cheshire` dependency?

**Comment by sroller** [comment]
Thank you, that was it! I was banging my head against the wall.
