### ISSUE TITLE
Links in the README table of contents are broken

### ISSUE THREAD

**Issue by jeremyheiler** [dakrone/clj-http#284]
I noticed that a handful of links in the README table of contents are broken. I started to go through and manually fix them, but then I realized that some links might be missing entirely. Maybe there's an automatic way of generating the table of contents to prevent it from getting out of date?

**Comment by dakrone** [comment]
> I noticed that a handful of links in the README table of contents are
> broken. I started to go through and manually fix them, but then I
> realized that some links might be missing entirely. Maybe there's an
> automatic way of generating the table of contents to prevent it from
> getting out of date?

That's correct, I was using https://github.com/snosov1/toc-org to
generate them. I should probably regenerate them.
