### ISSUE TITLE
Integer Multipart Param: "Body may not be null"

### ISSUE THREAD

**Issue by disalvjn** [dakrone/clj-http#287]
Multipart params cannot be numbers:
```clj
(clj-http.client/post "http://localhost" {:multipart [{:name "number" :content 1}]})
;; => IllegalArgumentException Body may not be null  org.apache.http.util.Args.notNull (Args.java:54)
```
In `clj-http.mutipart.create-multipart-entity`, the type of `(:content {:name "number" :content 1})` does not match any predicates in the `cond` clause, so `part` is bound to `nil`, which leads to the opaque error "Body may not be null." 

Is there a reason why there isn't an `else` clause where things that aren't strings/streams/files/byte-arrays are stringified and treated as strings? At least, a clearer error would be helpful.

**Comment by dakrone** [comment]
I see this issue, I think the `create-multipart-entity` method should throw an exception on a nil part. Would you like to open a PR for this?
