### ISSUE TITLE
Conflict with clojure.core/update

### ISSUE THREAD

**Issue by keorn** [dakrone/clj-http#289]
With Clojure 1.7.0: `WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update`

**Comment by dakrone** [comment]
This should be fixed already (see: https://github.com/dakrone/clj-http/issues/222) what version of clj-http are you using?

**Comment by keorn** [comment]
Sorry, did not notice it was not coming from my req, but a library that I am using: crawlista. It still uses 1.0, so will need to fix it there.
