### ISSUE TITLE
Anyway to specify the same query-params multiple times?  (duplicate keys)

### ISSUE THREAD

**Issue by joefromct** [dakrone/clj-http#291]
When fetching a response from some web services I believe it's needed to pass the same query param multiple times.

For instance, on a solr facet search as documented [here](https://wiki.apache.org/solr/SimpleFacetParameters#facet.field)
 
````
facet.field

This param allows you to specify a field which should be treated as a facet. 
It will iterate over each Term in the field and generate a facet count using 
that Term as the constraint.

This parameter can be specified multiple times to indicate multiple facet fields.
````
I'm not sure if there is a good way to do this with `clj-http` as the `query-params` receives a map and therefore cannot have duplicate key names.  Is there any workaround that is possible? 
````clojure
  (let [url "https://solr-url:8083/solr/some_core/select"]
  (->
   (client/get url
               {:as :json
                :query-params {"wt"          "json"
                               "q"           "text_stuff:search_word"
                               "fq"          "text_stuff:search_word"
                               "facet"       "true"
                               "facet.field" "field_1"
                               "facet.field" "field_2"
                               "facet.field" "field_3"
                               }
                }
               )
   :body
   :response
   )) 
````

Any tips appreciated, thanks in advance.

**Comment by joegallo** [comment]
If I understand your question correctly, I think you're just asking for this:

```
:query-params {"facet" "true"
               "facet.field" ["field_1" "field_2" "field_3"]}
```

That syntax is already built in and supported -- does it solve your problem?

**Comment by joefromct** [comment]
Yes, that works perfectly thanks.  I must have missed that in the documents/code.  Thanks again, -Joe
