### ISSUE TITLE
Can request just return the status code rather than throw on status codes other than 200s?

### ISSUE THREAD

**Issue by robertkuhar** [dakrone/clj-http#295]
Today I was surprised to learn "Exceptions are thrown for status codes other than 200-207, 300-303, or 307" in the request function of clj-http-1.1.0.jar clj_http/client.clj

This seems crazy to me as I expect any http client to only, you know, just run the HTTP protocol.  It should be up to my code to determine if a 403 is an exceptional condition or not.

There has got to be a better way to do this.  Can you have (request!) do the throws on not happy path and (request) just run the request, return the result, and let me figure it out?

This aspect of clj-http seems like overreach to me.  The library should just run the protocol and not force an exception handling strategy on me.

**Comment by dakrone** [comment]
It's in the [Exceptions](https://github.com/dakrone/clj-http#exceptions) part of the docs...

```clj
;; You can also ignore HTTP-status-code exceptions and handle them yourself:
(client/get "http://site.com/broken" {:throw-exceptions false})
```
