### ISSUE TITLE
client/get connection close time out

### ISSUE THREAD

**Issue by cloxure** [dakrone/clj-http#296]
After getting the response the http connection seems to remain open for a while (5 or more seconds). I am not sure if this is an expected behavior. 

The only thing that I am doing after I get the response is a simple print:

```clojure
(println (:body (client/get url {:accept :json})))
```

**Comment by cloxure** [comment]
PD: I am using the 2.0.0 version.

**Comment by cloxure** [comment]
PD: I am using the 2.0.0 version.

**Comment by dakrone** [comment]
@cloxure are you using a connection manager or anything like that?

**Comment by cloxure** [comment]
@dakrone I thought that too, but with or without the manager is the same thing.

**Comment by cloxure** [comment]
@dakrone  no. I am not using a connection manager.

**Comment by cloxure** [comment]
Here is my stack:
leiningen => 2.5.3
java 1.8.0_66
ubuntu 14.04.3 LTS

**Comment by cloxure** [comment]
@drakron any ideas?

**Comment by joegallo** [comment]
Can you provide a reproducible test case? I'm running the following, and it doesn't seem to take 5 seconds.

```clojure
user> (time (println (:body (client/get "http://jsonplaceholder.typicode.com/posts/1" {:accept :json}))))
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveni\
et architecto"
}
"Elapsed time: 470.327913 msecs"
```

**Comment by cloxure** [comment]
@joegallo  understood, I will bring you a reproducible scenario as soon as possible.

**Comment by joegallo** [comment]
Thanks! It's possible it could be client side, it's possible it could be server side, it's possible it's in some tricky edge case interaction involving both. Anyway, being able to see it action will absolutely help.

**Comment by cloxure** [comment]
@joegallo , @dakrone  you can close this issue. I found out the problem was with the server not the client. Thanks a lot.

**Comment by joegallo** [comment]
No worries, mate. Have a good one.
