### ISSUE TITLE
SOCKS5 Authentication Support

### ISSUE THREAD

**Issue by sgrove** [dakrone/clj-http#307]
I have a SOCKS5 proxy that requires authentication, and I'm unsure about how to pass that info along via the standard connection manager. I need to specify a proxy per-request, so I can't simply set the system properties. I've looked around in `conn_mgr.clj` but haven't seen anything that jumped out.

**Comment by dakrone** [comment]
@sgrove you can use the `:proxy-host` and `:proxy-port` settings on your clj-http request to set these per-request.

**Comment by sgrove** [comment]
This doesn't seem to work with SOCKS5, unless I'm missing something. I tried the `{:proxy-host "username@password:host" :proxy-port 1080}` format, and it fails (reasonably so). Is there any way to get this to work with a connection-manager?

**Comment by dakrone** [comment]
I believe this is fixed in #375
