### ISSUE TITLE
Support for custom http methods (like PROPFIND)  

### ISSUE THREAD

**Issue by xiexed** [dakrone/clj-http#312]
Trying to use clj-http as webdav client I faced that it does not support custom http methods, so
```
(client/request {
                                        :method "PROPFIND"
                                        :url "http://localhost:7000/"
                                        :Accept "*/*"
                                        :Depth "1"
                                        }
                                   ))
```

does not work for me:

```
java.lang.IllegalArgumentException: Invalid request method PROPFIND
            core.clj:206 clj-http.core/http-request-for
            core.clj:186 clj-http.core/http-request-for
            core.clj:268 clj-http.core/request
            core.clj:208 clj-http.core/request
            Var.java:379 clojure.lang.Var.invoke
          client.clj:801 clj-http.client/wrap-request-timing[fn]
```

Is there a way to workaround this? Or shouldn't support for custom methods be added?

**Comment by dakrone** [comment]
So, as far as my research shows, there is no support in Apache's HTTP client for the PROPFIND method, so you'd first need to write your own extension of the `HttpGet.java` class, and then you could redefine `clj-http.core/http-request-for` to include support for it.

Not sure how apache will treat it however...

**Comment by xiexed** [comment]
Finally I've settled down with using raw Apache Client and

```clojure
(proxy [HttpRequestBase] [] (getMethod []
                               (str "PROPFIND")))
```

worked fine for me. 

I am not sure in my Clojure skills but maybe I will try to fix it and send a pull request
