### ISSUE TITLE
Why are the default timeouts -1 forever?

### ISSUE THREAD

**Issue by timothypratley** [dakrone/clj-http#315]
Shouldn't the default timeouts to something reasonable like 10 seconds?

**Comment by dakrone** [comment]
> Shouldn't the default timeouts to something reasonable like 10 seconds?

I left them at the Apache defaults (unset), do you have a reason why
they should be shorter? (I have no opinion, I just left them at the
default, but I'm open to changing them)

**Comment by timothypratley** [comment]
Hi Lee,


IMO unbounded operations are a bit of a smell.
Just like waiting for a lock indefinitely is likely to leave my system crippled,
waiting for a response indefinitely will do too.
Here is a great talk on why locks should always have a timeout:
https://www.youtube.com/watch?v=yhguOt863nw
I don't have any links to anyone evaluating socket timeout merits in depth, but my opinion is that the same reasons hold true.

My desire for defaults comes from finding that when I omit them, I often spend a lot of time diagnosing something that would have been obvious with a timeout, and end up always having a timeout specified.

Having said all that, I do think it is a good policy to follow the Apache defaults. However from looking at the code it does seem like they are explicitly set to -1 (in HEAD). In any case, it would be a difficult change to justify given it could be potentially breaking for some people... So I can't realistically push for it.

I'm interested in how best to approach this desire to have my connections be bounded... remembering to add the timeouts everywhere is a little wordy and prone to mistakes because for example in clojurescript the keyword is :timeout but in clojure it is :socket-timeout and :conn-timeout. And or if there are any good references on why unbounded is better.


Regards,
Timothy
