### ISSUE TITLE
*cookie-store* in core no longer supported?

### ISSUE THREAD

**Issue by lianxiangru** [dakrone/clj-http#318]
I cannot use it in the lastest version. Is there any other usage that can substitute the `*cookie-store*`?

**Comment by dakrone** [comment]
@lianxiangru hmm.. looking at the code for it, the support is still there, can you describe the problem you're seeing with it? It may end up being a bug

**Comment by lianxiangru** [comment]
@dakrone Hi! I have read the code, only the `core_old.clj` file contains `*cookie-store*`. It appears in the definition of this dynamic variable and the `request` function.
Both are deleted in the `core.clj`.

**Comment by dakrone** [comment]
Ahh okay, it looks like when I added the cookie store - https://github.com/dakrone/clj-http/blob/master/src/clj_http/core.clj#L276-L277 I only added the support for the `:cookie-store` key in the option map and not `*cookie-store*`. I can re-add that in. In the meantime, you can pass the store with `:cookie-store` in your requests

**Comment by lianxiangru** [comment]
Also, the behavior of cookie store in `core.clj` and `core_old.clj` are different.

In old version ([clj-http "2.1.0"]) I have
```clojure
(let [cookie-store (clj-http.cookies/cookie-store)]
  (client/get "http://zhihu.com" {:cookie-store cookie-store})
  (print (clj-http.cookies/get-cookies cookie-store)))
=> {_xsrf {:discard true, :domain www.zhihu.com, :path /, :secure false, :value 627eb084f45cd6d7d6f42489ca6fc5f3, :version 0}, cap_id {:discard false, :domain zhihu.com, :expires #inst "2016-05-18T14:36:31.000-00:00", :path /, :secure false, :value "NjA0MjZmYjFlY2YxNGEyMWJmNzIyMDkyNWJhMGM4YWU=|1460990191|cf88dbb83f5f49e0e39ac2061e7d830f1f1876fd", :version 0}, l_cap_id {:discard false, :domain zhihu.com, :expires #inst "2016-05-18T14:36:31.000-00:00", :path /, :secure false, :value "ZTdhNjc4NTFhNzQyNDExMDg2YTc0ZGY2NWU2NjdlZmQ=|1460990191|af86b27c05c85bf4052ddb4cffce4396dea2c781", :version 0}, l_n_c {:discard true, :domain zhihu.com, :path /, :secure false, :value 1, :version 0}, n_c {:discard true, :domain zhihu.com, :path /, :secure false, :value 1, :version 0}, q_c1 {:discard false, :domain zhihu.com, :expires #inst "2019-04-18T14:36:31.000-00:00", :path /, :secure false, :value 78bec6726d054f51b721412df40497ae|1460990191000|1460990191000, :version 0}}
```
In the new version ([clj-http "RELEASE"]) with the same code I have
```clojure
(let [cookie-store (clj-http.cookies/cookie-store)]
  (client/get "http://zhihu.com" {:cookie-store cookie-store})
  (print (clj-http.cookies/get-cookies cookie-store)))
=> {_xsrf {:discard true, :domain www.zhihu.com, :path /, :secure false, :value 35d9ed038e614a3ce2ae0e8f2ae0ca3d, :version 0}, l_n_c {:discard true, :domain zhihu.com, :path /, :secure false, :value 1, :version 0}, n_c {:discard true, :domain zhihu.com, :path /, :secure false, :value 1, :version 0}}
```
This actually causes some operations like loggging in failure in the new version. Is this a bug in the new version?

**Comment by dakrone** [comment]
@lianxiangru the actual behavior of the cookie store itself I haven't touched, the only thing that has changed has been an Apache HTTP version upgrade, it sounds like perhaps that might be what's causing this?

**Comment by lianxiangru** [comment]
@dakrone Probably, let me change it back to `4.5.1` to see whether it works.

**Comment by lianxiangru** [comment]
@dakrone Still not working.
```clojure
user=> (let [cookie-store (clj-http.cookies/cookie-store)]
  #_=>   (client/get "http://zhihu.com" {:cookie-store cookie-store})
  #_=>   (print (clj-http.cookies/get-cookies cookie-store)))
{_xsrf {:discard true, :domain www.zhihu.com, :path /, :secure false, :value ac799097c4ac9ad579435efdc55747e1, :version 0}, l_n_c {:discard true, :domain zhihu.com, :path /, :secure false, :value 1, :version 0}, n_c {:discard true, :domain zhihu.com, :path /, :secure false, :value 1, :version 0}}nil
```
It still returns the shorter cookie even with the older `4.5.1` dependency:
```clojure
  :dependencies [[org.apache.httpcomponents/httpcore "4.4.4"]
                 [org.apache.httpcomponents/httpclient "4.5.1"]
                 [org.apache.httpcomponents/httpmime "4.5.1"]
                 [commons-codec "1.10"]
                 [commons-io "2.4"]
                 [slingshot "0.12.2"]
                 [potemkin "0.4.3"]]
```

**Comment by dakrone** [comment]
Closing this for now since it's old and the user has deleted their profile, we can re-open if anyone else sees it.
