### ISSUE TITLE
make-socks-proxied-conn-manager doesn't work

### ISSUE THREAD

**Issue by jstewart** [dakrone/clj-http#330]
I tried to use a SOCKS5 connection per the documentation and got a ClassCastException.

Started a SSH proxy locally:

`ssh -N -D 0.0.0.0:1080 localhost`

Then tried using this connection as per the docs:

`(clj-http.client/get "http://www.google.com", {:connection-manager (clj-http.conn-mgr/make-socks-proxied-conn-manager "localhost" 1080)})`

Get the following ClassCastException:

`java.lang.ClassCastException: org.apache.http.impl.conn.PoolingClientConnectionManager cannot be cast to org.apache.http.conn.HttpClientConnectionManager`

**Comment by dakrone** [comment]
I think this is a leftover from the move to non-deprecated APIs, the socks proxy connection manager is still using the deprecated one, so it cannot be cast. I'll check it out

**Comment by taeold** [comment]
I believe #328 fixes this.

**Comment by dakrone** [comment]
@jstewart can you test with the latest master and see if this has already been fixed?

**Comment by jstewart** [comment]
@dakrone Excellent. Yes, SOCKS proxying works again now with the latest master.

**Comment by dakrone** [comment]
@jstewart great, I will make a release as soon as I get stable internet

**Comment by dakrone** [comment]
Released 3.2.0 that has this fixed
