### ISSUE TITLE
Sending a :form-param param with vector value always results in indexed style of params

### ISSUE THREAD

**Issue by RokLenarcic** [dakrone/clj-http#336]
I'm running version 2.2.0.
I have a problem where I'm required to POST form params such as "a=1&a=2&a=3".

Here's the code:
```
(client/post "http://www.google.com" {:form-params {:a [1 2 3]}})
```
Instead of expected default style of `a=1&a=2&a=3`, I get the following:

`a[0]=1&a[1]=2&a[2]=3`

See attached Wireshark capture for the request to google above:

<img width="632" alt="screen shot 2016-10-14 at 02 03 58" src="https://cloud.githubusercontent.com/assets/3322433/19371442/4d2d9fa4-91b3-11e6-93f3-b66973d08fc5.png">

Is there a way I can change this?

**Comment by dakrone** [comment]
I don't think there is currently a way to change this, we'll need to add something for `:form-params` similar to the `:multi-param-style` added for the query string parameters.

**Comment by RokLenarcic** [comment]
Is there a way I could manually achieve this?

**Comment by RokLenarcic** [comment]
But what about this:

`https://github.com/dakrone/clj-http/blob/master/src/clj_http/client.clj#L753`

Doesn't that take multi-param-style as parameter?

**Comment by RokLenarcic** [comment]
Works with 3.3.0.
