### ISSUE TITLE
`follow-redirects` + `wrap-cookies` => problem

### ISSUE THREAD

**Issue by cch1** [dakrone/clj-http#345]
When using the default middleware, wrap-redirects happens lower in the middleware and thus the  wrap-cookies middleware never sees cookies set on the redirect response.

**Comment by cch1** [comment]
One partial solution is to use custom middleware, but reordering is _challenging_.  For example, one needs to send the `:follow-redirects false` option somehow between the two.

**Comment by dakrone** [comment]
Does this still occur now that #341 is merged? It changed the way redirects are handled

**Comment by cch1** [comment]
I looked at what is required to update my use of clj-http to try this new version... I probably won't be able to test it soon.  Can you outline the changes to redirect following *particularly with respect to cookie management*?  Also, what are the alternatives and best practices for using clj-http with cookies?  I see several mechanisms in the code and I'm not sure which will be supported going forward.

**Comment by dakrone** [comment]
>  Can you outline the changes to redirect following particularly with respect to cookie management?

Rather than handling redirects on the client side in clj-http middleware, the redirects are now handled by the Apache HTTP client itself, so I am guessing the cookie management may be better, since I never did anything special with cookies and redirects in the past.

**Comment by cch1** [comment]
I've been able to test this now, and the problem remains.  The issue is almost certainly that cookie headers on 3XX responses are never seen by the `wrap-cookies` middleware and thus any cookies set at that point are lost.

Given that the direction seems to be to let the underlying library manage redirects, it should also be used for cookie management.

**Comment by cch1** [comment]
In order to properly manage cookies for multiple requests (possibly including redirects), I have found the best solution to be a combination of removing the `wrap-cookies` middleware and writing my own that shuttles cookies from an external cookies map into a `CookieStore` object supplied to the request.  The only remaining downside to this approach is that clj-http does not support providing an `HttpClientContext` and so it's not possible to preserve session (`discard=true`) cookies across requests without tweaking the session cookies to look like permacookies.

Long term, it would be nice if clj-http allowed an `HttpClientContext` to be provided on each request.  This would have the effect of allowing the caller to determine the extent of the session -something that clj-http generally defers on managing.

Here is the middleware that I use to handle cookies:

```
(defn wrap-cookie-store
  "Generate clj-http-client to adapt requests to a session and update the session from the response"
  [session]
  (fn wrap-cookie-store-middleware [client]
    (fn cookie-store-wrapper [rq]
      (let [c-store (let [cs (cookies/cookie-store)]
                      ;; Hack session cookies to survive *across* native sessions since we can't manage them
                      ;; http://stackoverflow.com/questions/6272575/how-to-handle-the-session-in-httpclient-4-1
                      (doseq [cp (map (fn [[k v]] [k (assoc v :discard false)]) (-> session deref :cookies))]
                        (let [c (cookies/to-basic-client-cookie cp)]
                          (cookies/add-cookie cs c)))
                      cs)
            rs (-> rq
                  (assoc :cookie-store c-store :cookie-policy :standard)
                  client)]
        (reset! session (-> @session
                           (update :cookies merge (cookies/get-cookies c-store))))
        rs))))
```

**Comment by dakrone** [comment]
> Long term, it would be nice if clj-http allowed an `HttpClientContext` to be provided on each request.

I don't see any reason this shouldn't be an option, would you like to open a PR that allows configuring this per-request?

**Comment by cch1** [comment]
Mechanically, it would not be hard.  But I think that the semantics of providing an HttpClientContext might be challenging when a CookieStore and/or a RedirectStrategegy are supplied.

**Comment by lvh** [comment]
I hit this problem too. However, in the current value of `default-middleware`, there is no wrap-redirects anymore?

**Comment by lvh** [comment]
@cch1 Is there a specific spot the middleware should go?

**Comment by cch1** [comment]
That depends on your use case.  Here is what I have done:

```
> (defn- wrap-cookie-store
>   "Generate clj-http-client to adapt requests to a session and update the session from the response"
>   [session]
>   (fn wrap-cookie-store-middleware [client]
>     (fn cookie-store-wrapper [rq]
>       (let [c-store (let [cs (cookies/cookie-store)]
>                       ;; Hack session cookies to survive *across* native sessions since we can't manage them
>                       ;; http://stackoverflow.com/questions/6272575/how-to-handle-the-session-in-httpclient-4-1
>                       (doseq [cp (map (fn [[k v]] [k (assoc v :discard false)]) (-> session deref :cookies))]
>                         (let [c (cookies/to-basic-client-cookie cp)]
>                           (cookies/add-cookie cs c)))
>                       cs)
>             rs (-> rq
>                   (assoc :cookie-store c-store :cookie-policy :standard)
>                   client)]
>         (reset! session (-> @session
>                            (update :cookies merge (cookies/get-cookies c-store))))
>         rs))))
> 
> (defn- wrap-relative-url
>   "Generate clj-http client to handle relative URLs"
>   [session]
>   (fn wrap-relative-url-middleware [client]
>     (fn relative-url-wrapper [rq]
>       (let [{:keys [history]} @session
>             rq (update rq :url (fn [u] (str (URL. (or (last history) *uri*) u))))]
>         (reset! session (-> @session
>                            (update :history conj (URL. (:url rq)))))
>         (client rq)))))
> 
> (defn- wrap-user-agent
>   [id]
>   (fn [client]
>     (fn [rq]
>       (client (assoc-in rq [:headers :user-agent] id)))))
> 
> (defn request
>   [session rq]
>   ;; https://github.com/dakrone/clj-http/issues/345
>   (http/with-middleware [http/wrap-request-timing
>                          http/wrap-async-pooling
>                          wrap-header-map
>                          http/wrap-query-params
>                          http/wrap-basic-auth
>                          http/wrap-oauth
>                          http/wrap-user-info
>                          http/wrap-url
>                          http/wrap-decompression
>                          http/wrap-input-coercion
>                          ;; put this before output-coercion, so additional charset
>                          ;; headers can be used if desired
>                          http/wrap-additional-header-parsing
>                          http/wrap-output-coercion
>                          http/wrap-accept
>                          http/wrap-accept-encoding
>                          http/wrap-content-type
>                          http/wrap-form-params
>                          http/wrap-nested-params
>                          http/wrap-method
>                          wrap-links
>                          http/wrap-unknown-host
>                          (wrap-user-agent "APIJ Integration Test")
>                          (wrap-cookie-store session)
>                          (wrap-relative-url session)]
>     (http/request rq)))
> 
```

`

**Comment by dakrone** [comment]
clj-http does provide the ability to specify your own `HttpClientContext` now, with the `:http-client-context` option, so I'm going to close this for now. Let me know if we should re-open it.
