### ISSUE TITLE
Turn clj-http.core/get-cookie-policy into multimethod

### ISSUE THREAD

**Issue by martinklepsch** [dakrone/clj-http#349]
We work with some systems that return invalid cookies and thus need to be able to customize the cookie policy. Would you be interested in a PR that changes [`get-cookie-policy`](https://github.com/dakrone/clj-http/blob/3.4.1/src/clj_http/core.clj#L84-L91) into a multimethod so it can be extended by users?

Thanks for your time!

**EDIT** Maybe it's not that simple, will update...

**EDIT2** Ok, assuming [the docs here (see point 3.4)](https://hc.apache.org/httpcomponents-client-ga/tutorial/html/statemgmt.html) are up to date a multimethod should be sufficient. The registry is a stateful thing maintained by the library itself.

**EDIT3** After re-reading the snippet in in the docs under 3.4 it became apparent that this would also require a way to pass in a custom `CookieSpecProvider` [here](https://github.com/dakrone/clj-http/blob/3.4.1/src/clj_http/core.clj#L134). Welcome to the kingdom of nouns!

**Comment by dakrone** [comment]
Martin Klepsch writes:

> We work with some systems that return invalid cookies and this need to
> be able to customize the cookie policy. Would you be interested in a
> PR that changes
> [`get-cookie-policy`](https://github.com/dakrone/clj-http/blob/3.4.1/src/clj_http/core.clj#L84-L91)
> into a multimethod so it can be extended by users?

Sure, I'd definitely accept that. It looks pretty simple and it's an
easy extension point as you said.

--
;; Lee

**Comment by dakrone** [comment]
@martinklepsch okay, I'm still game if it can be accomplished and if you'd like to try it :)

**Comment by dakrone** [comment]
@martinklepsch I've pushed the change to make this a multi-method. Let me know if that works for you. I know you mentioned the cookie spec provider, if you still need this can you open a separate issue for it and I'll work on it?
