### ISSUE TITLE
Is it possible to send body in the GET request?

### ISSUE THREAD

**Issue by avichalp** [dakrone/clj-http#350]
I am using clj-http to issue queries on elaticsearch through REST API.
I want to issue the following query:
```
curl -XGET "http://localhost:9200/test/_search" -d' {"from":0,"size":1000}'
```

I could not find any documentation on how to send data with GET request.

**Comment by dakrone** [comment]
You certainly can, it's just like a `post` request, but `get` instead :)

```clojure
(http/get "http://localhost:9200/test/_search" {:body (json/encode {:from 0, :size 1000})})
```

**Comment by avichalp** [comment]
@dakrone Thanks :)
