### ISSUE TITLE
`ReuseableAsyncConnectionManager` not considered `reusable` v3.4.1

### ISSUE THREAD

**Issue by marctrem** [dakrone/clj-http#355]
![screen shot 2017-03-07 at 5 17 10 pm](https://cloud.githubusercontent.com/assets/1619947/23685654/16eec6a2-035a-11e7-8f64-b9b38e6a9c86.png)

Is that the expected behavior?

conn-mgr is of type `clj_http.conn_mgr.proxy$org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$ReuseableAsyncConnectionManager$fff3515b` and it does not pass the `reusable?` test.

**Comment by marctrem** [comment]
With further invenstigation: the check passes if it is looked as being a member of `PoolingNHttpClientConnectionManager`

**Comment by dakrone** [comment]
@marctrem is this biting your in an application? I added a test for this, but it doesn't seem to reproduce?

**Comment by dakrone** [comment]
Closing as there has been no feedback, feel free to comment if this was closed erroneously.
