### ISSUE TITLE
Make IOReactor configurable

### ISSUE THREAD

**Issue by bentomi** [dakrone/clj-http#360]
The IOReactor used by the asynchronous connection manager has many [configuration options](https://hc.apache.org/httpcomponents-core-ga/httpcore-nio/apidocs/org/apache/http/impl/nio/reactor/IOReactorConfig.Builder.html) that are currently not accessible. This issue is about providing access to them.

We have to decide how we present these configuration options:
1. flat, together with the existing options like `:threads`, `:insecure?` etc.
1. as a map under a separate key, e.g., `:io-reactor-config`.

Should these options be available as request options or only in `with-connection-pool`?

Points to consider:
1. some configuration options are present in multiple places (e.g., connection timeout, socket timeout)
1. the IOReactor is only used for async requests.

@dakrone, please advise.

**Comment by dakrone** [comment]
> Should these options be available as request options or only in with-connection-pool?

I think it makes sense only to use them with `with-connection-pool` (or pre-creating a connection-manager and passing it with `:connection-manager`). Especially since these are fairly advanced settings I don't expect everyone to be setting.

> We have to decide how we present these configuration options:

I *think* I'm in favor of # 2, perhaps as a map in `:io-config`, what do you think?

**Comment by bentomi** [comment]
I'm in favour of # 2 and `:io-config` sounds basically good, except that the options would have an effect only for async connection pools. So maybe `:async-io-config` would make more sense. Or do you see a way to provide (some of) these options for synchronous connections too?

**Comment by dakrone** [comment]
let's call them `:io-config` in the event they do end up being applied to non-async connection pools in the future, and we can just ignore them for now on non-async connection managers

**Comment by bentomi** [comment]
@dakrone, please have a look at eb2daaf699e751fa933538a8305ea90848d06d9f, I have some questions releated to it.

1. Does this change really make sense for HTTP?
1. Do all of the options make sense?
1. Should these options be documented? (Do we want to commit to supporting them in the future?)
1. How would you test?

**Comment by dakrone** [comment]
> Does this change really make sense for HTTP?

It seems like some users may want to be able to change these settings, I don't see why they wouldn't make sense.

> Do all of the options make sense?

They make sense for the most part, I haven't really dug into their exact behavior, but the docstring seems clear enough

> Should these options be documented? (Do we want to commit to supporting them in the future?)

I think just adding them to the docstring is enough, they're pretty advanced settings so I don't expect they need to be fully documented in the readme.

> How would you test?

This is the most annoying for things like this, stuff like connection timeouts and number of threads etc are all a big pain to write tests for. For now, I would manually test until we figure out if there's a better way.

**Comment by bentomi** [comment]
OK. Should I fix/add something before I make a pull request?

**Comment by dakrone** [comment]
> Should I fix/add something before I make a pull request?

You can go ahead and make a PR, then I'll give it a more thorough review!
