### ISSUE TITLE
Can't send :form-params with method :delete

### ISSUE THREAD

**Issue by DanBurton** [dakrone/clj-http#365]
I'm dealing with a legacy server, and I need to send it a `DELETE` request with form params. I know. This is weird and unusual, but I'm not at liberty to modify the legacy server, I just have to deal with it.

It would be nice if clj-http would let me do this. It seems to discard `:form-params`. Here's a minimal test case to illustrate:

https://gist.github.com/DanBurton/93c6abe8c21040ad572664e126345916

**Comment by dakrone** [comment]
Resolved by #366

**Comment by dakrone** [comment]
@DanBurton I will do a release with this fix in very soon, I am waiting to (hopefully) get #362 in before releasing, if it doesn't happen soon I'll do a bugfix release with your fix

**Comment by DanBurton** [comment]
Awesome, thanks for the quick response!

**Comment by dakrone** [comment]
This is available in clj-http 3.5.0 now
