### ISSUE TITLE
Example caching middleware

### ISSUE THREAD

**Issue by carld** [dakrone/clj-http#367]
Hi, I'm new to clojure and attempted to implement a TTL based caching middleware for clj-http.

By looking at the included middleware functions in clj-http I came up with the following, which appears to work, but I'd appreciate any feedback, thanks
```clojure
(def http-cache (atom (cache/ttl-cache-factory {} :ttl (* 60 60 1000))))

(defn- cached-response
  ([client req]
   (let [cache-key (str (:server-name req) (:uri req) "?" (:query-string req))]
     (if (cache/has? @http-cache cache-key)
       (do
         (println "CACHE HIT")
         (client req (reset! http-cache (cache/hit @http-cache cache-key)) nil ) )
       (do
         (println "CACHE MISS")
         (reset! http-cache (cache/miss @http-cache cache-key (client req))))
       ))))

(defn wrap-caching-middleware
  [client]
  (fn
    ([req]
     (cached-response client req))))
```

**Comment by carld** [comment]
For what it's worth the above had at least two bugs, 1) in the case of a cache miss the client function was not being called and an exception was being thrown somehow by the redirect middleware, 2) every was being cached, including redirects and error responses. The code below tries to fix those bugs

```
(defn- cached-response
  ([client req]
   (let [cache-key (str (:server-name req) (:uri req) "?" (:query-string req))]
     (if (cache/has? @http-cache cache-key)
       (do
         (println "CACHE HIT")
         (client req (reset! http-cache (cache/hit @http-cache cache-key)) nil ) )
       (do
         (println "CACHE MISS")
         (let [resp (client req)]
           (if (client/success? resp)
             (do
               (reset! http-cache (cache/miss @http-cache cache-key resp))
               (client req resp nil))
             (do
               (client req resp nil)))))))))
```

**Comment by dakrone** [comment]
@carld if you're interested, you could submit this as an example in the `examples/` directory (submit it as a PR) and I'd be happy to give it a real review, it's much easier to comment there since I can make line-by-line comments

**Comment by carld** [comment]
@dakrone  👍  thanks! I have submitted PR #368 and am closing this.
