### ISSUE TITLE
Low-level customization of CloseableHttpClient

### ISSUE THREAD

**Issue by serioga** [dakrone/clj-http#371]
I did not find a way to manage keep-alive strategy or connection reuse strategy for underlying `CloseableHttpClient` in version 3.5.0.

It would be great to have access to low-level customization of the client, i.e. via custom handler for client builder.

**Comment by dakrone** [comment]
@serioga I have added this in https://github.com/dakrone/clj-http/pull/434 let me know if that isn't enough customization for you!

**Comment by serioga** [comment]
Well, this allows me to configure builder as I want.
But as I see builder functions are called on every request what does not look perfect 😕

**Comment by serioga** [comment]
Ah, I see in HELP WANTED :-)

> Additionally, there are things like reusing the httpclient between requests (perhaps only when a connection manager is used) that need to be worked out.

**Comment by dakrone** [comment]
@serioga I opened an issue to investigate HttpClient between requests at https://github.com/dakrone/clj-http/issues/441
