### ISSUE TITLE
why is :redirect-strategy needed for :follow-redirects?

### ISSUE THREAD

**Issue by facundoolano** [dakrone/clj-http#372]
Hi, I'm using version "3.5.0" of the library and I need to make a request that does not follow redirects (I expect to get a 302 response and a populated location header). To do so I've tried setting `:follow-redirects false` in the options, but that seems to be ignored unless I set `:redirect-strategy` to either `:none` or `:graceful`. I didn't see the strategy option mentioned in the README, so I'm wondering why is it needed for the follow-redirects option to work.

**Comment by dakrone** [comment]
Hmm.. that doesn't seem like it should be required as you say. I think this is a bug. I think `:follow-redirects false` should do whatever is necessary to ignore redirects

**Comment by facundoolano** [comment]
I see. Some code to reproduce the behavior (apparently only `:redirect-strategy :none` makes the option work):

```clojure
user> (:status (http/get "http://httpbin.org/redirect/1"))
200
user> (:status (http/get "http://httpbin.org/redirect/1" {:follow-redirects false}))
200
user> (:status (http/get "http://httpbin.org/redirect/1" {:follow-redirects false :redirect-strategy :none}))
302
user> (:status (http/get "http://httpbin.org/redirect/1" {:follow-redirects false :redirect-strategy :graceful}))
200
```

**Comment by atroche** [comment]
Thanks for posting this, it just tripped me up too.

**Comment by bo-chen** [comment]
This also works:

```
=> (:status (http/get "http://httpbin.org/redirect/1" {:max-redirects 0 :redirect-strategy :graceful}))
302
```

**Comment by rymndhng** [comment]
Sorry about that, this trips people up because there's currently two ways of doing redirects. Since the 3.x.x branch, there are two pieces of code that handle redirects:

- the old clj-http middleware (deprecated)
- the new way (by configuring the Java HTTP Client)

So, unfortunately the only way to turn off redirects is to turn off both systems of following redirects:

- disable the clj-http middleware `:follow-redirects` false
- disable the Java HTTP Client Config `:redirect-strategy :none`

---

@dakrone What are your thoughts around this? I think we should get rid of the deprecated redirects middleware. The old `:follow-redirects` flag *could* be translated into `:follow-redirects :graceful` (it was meant to preserve the old behaviour). We should warn users if they try to use both `:follow-redirects` and `:redirect-strategy` in the same options map though, because we would not be able to figure out which one has precedence.

**Comment by eigenhombre** [comment]
This definitely seems like a bug either in the implementation or the documentation (at least in 3.7.0).  `:follow-redirects` by itself seems to be useless.  Thanks for the `:redirect-strategy :none` tip on this ticket!

**Comment by rymndhng** [comment]
I added a PR to address some of the documentation issues. Would love if folks could read it over to see how it could be improved to onboard folks to the library better :)

**Comment by facundoolano** [comment]
With that PR the documentation isn't misleading anymore, but I got to say, while I understand the new API opens up flexibility to handle more sophisticated cases, it feels it got less readable and intuitive for the most frequent cases (at least the ones _I_ found frequently).

- I think by default you want to follow redirects. 
- Sometimes you'll want to turn them off, and get the 30x status response instead. In that case `:follow-redirects false` perfectly reflects your intention; `:redirect-strategy :none`, not so much.
- Maybe you want to follow a given number of redirects, before getting the 30x status. `:max-redirects 3` conveys it, but now you have to add `:redirect-strategy :graceful` if you don't want to get exceptions, which sounds like a better default.
- If you do want exceptions, then `:throw-exceptions true` makes it clear.

I'm not saying you should drop the redirect strategies, just that as a library user I would prefer defaults closer to what the previous versions did.

**Comment by rymndhng** [comment]
@facundoolano Completely agree with your first two points! I liked the old defaults (hence adding a :graceful strategy). 

One of the things that made it complicated is that 3.x changed the redirect behaviour and to make it better more compatible to 2.x -- it would mean breaking 3.x again. Kind of a bind :/ 

Maybe this is something we can look forward to if clj-http goes to the 4.x where we can break the APi and make the defaults better.

**Comment by dakrone** [comment]
@facundoolano I agree with you, it's definitely a tradeoff of the flexibility with more complexity

> Maybe this is something we can look forward to if clj-http goes to the 4.x where we can break the APi and make the defaults better.

I'd love for folks to weigh in with what they'd like to see (for 4.x, so assuming you can break options) that retains the power but is a simpler interface for users!
