### ISSUE TITLE
Does clj-http correctly handle self-signed certificates?

### ISSUE THREAD

**Issue by doomchild** [dakrone/clj-http#376]
I've got a service that I hit in Java using a particular keystore and password.  Using the same keystore and password in clj-http 3.5.0, I'm getting `SunCertPathBuilderException unable to find valid certification path to requested target` errors when doing a GET.  The server is using a self-signed certificate, and I've seen at least one other issue in here talking about problems with those.  Is that still a problem, or should I be looking somewhere else?

**Comment by dakrone** [comment]
I believe it should handle it with the correct keystore, do you have an example I could retry to reproduce it?

**Comment by doomchild** [comment]
I don't have one right this second (my current version hits some of our internal stuff), but give me a day or two and I should be able to hack something together.

**Comment by doomchild** [comment]
Okay, it didn't take me as long as I thought it would.  This is a little messy, but it shows what I'm hitting.

The server is in `server.js`.  The PEM and KEY files were generated as a self-signed cert, and then I made a JKS file out of them as well (PEM and KEY for the node server, JKS for Clojure).

[https_test.zip](https://github.com/dakrone/clj-http/files/1024164/https_test.zip)

If I run the server, then try to hit it with the following Clojure snippet, I get the above error.

```
(ns client.client
  (:require [clj-http.client :as clj]))

(defn get-client [base-url keystore keystore-pass]
  {:url base-url
   :keystore keystore
   :keystore-pass keystore-pass
   :accept :json
   })

(defn get [client]
  (clj/get (:url client) (dissoc client :url)))
```

**Comment by RokLenarcic** [comment]
Did you try adding self-signed cert to your JVM's truststore?

**Comment by dakrone** [comment]
I'll look into adding documentation for how to get this set up and working.

**Comment by dakrone** [comment]
@doomchild I pushed a new file (<https://github.com/dakrone/clj-http/blob/master/SSL.org>) where I document how to do this, let me know if it doesn't work for you!

**Comment by doomchild** [comment]
Excellent.  Thanks a lot!
