### ISSUE TITLE
No socket timeout exception when :throw-exceptions set to true? 

### ISSUE THREAD

**Issue by GEverding** [dakrone/clj-http#379]
Seeing this weird behaviour in production where if I set `socket-timeout` and `conn-timeout` and set `throw-exceptions` to `false` I don't see `SocketTimeoutException` but when I set `throw-exceptions` to `true` I see `SocketTimeoutException` in sentry. In the case when I set `throw-exceptions` to `false` I think its not timing out when it should and its just hanging forever. I'm basing this on the fact that I've only caught a SocketTimeout in sentry after changing throw-exceptions from false to true last night after my application locked up. 

Is this possible?  

I'm still looking at this on my end and i'm using 3.6 now (upgraded from 2.3.0 last night to try and resolve the issue).

**Comment by rymndhng** [comment]
It shouldn't, `:throw-exceptions` is meant to transform `unexceptional` HTTP status codes into exceptions. It does not swallow exceptions that are thrown from the underlying Java HTTP Client.

**Comment by dakrone** [comment]
Are you able to reproduce the hanging? If so, can you share what you are using to reproduce it?

**Comment by dakrone** [comment]
Closing as there has been no feedback, feel free to comment if this was closed erroneously.
