### ISSUE TITLE
UnsupportedSchemeException http protocol is not supported, thrown when doing requests with client certificates via http proxy

### ISSUE THREAD

**Issue by ayoyoness** [dakrone/clj-http#380]
With a direct connection to the internet, one would simply use a connection manager with the keystore registry scheme (providing `:keystore` and/or `:trust-store`), to successfully make requests with a client and/or server ssl certificates.
However, this would not work if the connection has to go through a http proxy.
With the setup:
``` client (https) <-> proxy (http) <-> server (https)```
the current implementation will throw an `UnsupportedSchemeException http protocol is not supported`.
This is because we [only register](https://github.com/dakrone/clj-http/blob/master/src/clj_http/conn_mgr.clj#L148) the https socket factory with the current [keystore registry scheme](https://github.com/dakrone/clj-http/blob/master/src/clj_http/conn_mgr.clj#L142-L149) implementation.
Meanwhile,  connections through a http proxy would still need the initial CONNECT request  via `http` protocol before  tunneling of actual `https` connection to the server could be done. Ergo, we would still need a http socket factory in the registry.

To fix,
we would just need to register a plain socket factory for http, as [we do](https://github.com/dakrone/clj-http/blob/master/src/clj_http/conn_mgr.clj#L98) in the regular scheme.

I could do a PR but just want to check that what i'm saying is making sense or whether there is a way to do this with the current implementation, that i might have missed.

**Comment by dakrone** [comment]
> we would just need to register a plain socket factory for http, as we do in the regular scheme.

+1 to do this, good catch @ayoyoness, feel free to open a PR!

**Comment by aiba** [comment]
FWIW, this is what's preventing me from upgrading from 2.3.0 to 3.6.0.  So in case it's helpful, this worked in 2.3.0.

I didn't open an issue because I thought surely I was the only weirdo using clojure and https client certificates via an http proxy.  Lesson learned.  Thank you so much for figuring this out!

**Comment by aiba** [comment]
I just verified that adding `(.register "http" (PlainConnectionSocketFactory/getSocketFactory))` after line 147 of `conn_mgr.clj` works.  I'll let @ayoyoness do the honors of this 1-line PR.

**Comment by ayoyoness** [comment]
done

**Comment by enragedginger** [comment]
Do we have an estimate on when this will be resolved and merged? I'm also experiencing this issue.

**Comment by dakrone** [comment]
@enragedginger the PR has been merged and 3.6.2 released with this fix.

**Comment by dakrone** [comment]
Resolved by #381

**Comment by enragedginger** [comment]
Thank you!

**Comment by enragedginger** [comment]
@dakrone It looks like there is a version 3.6.1 available on Clojars, but not a 3.6.2. Which version has the fix?

**Comment by dakrone** [comment]
@enragedginger whoops! I typoed, I meant 3.6.1 (which has the fix)

**Comment by enragedginger** [comment]
Cool. Thanks again!
