### ISSUE TITLE
Cannot specify separate form field name and file name in multipart file upload

### ISSUE THREAD

**Issue by harold** [dakrone/clj-http#387]
First, thanks for this library, it generally does a great job and we use it to good effect in many places and really like the api and the overall attention to detail in its operation.

If I am reading this correctly:
https://github.com/dakrone/clj-http/blob/72f531f00d099f9676c60e2891c12d412b2a3a53/src/clj_http/multipart.clj#L36

When the `FileBody` object is constructed, its filename is either set to the form field name or is not provided (in which case it defaults to copying the filename of the provided file).

Ideally, I'd like to specify the form field name and the filename separately. In fact, I need to do to appease the server I'm posting to.

Thanks in advance for your time and consideration.

**Comment by dakrone** [comment]
Looking at the code, you should be able to use `:part-name` for the part name, and `:name` for the filename to be used for the actual `FileBody`, does that work for you?

**Comment by harold** [comment]
Ah! Neat. I had missed `:part-name`. That definitely gets me going; thank you!
