### ISSUE TITLE
is it possible to disable the retry feature?

### ISSUE THREAD

**Issue by pablobcb** [dakrone/clj-http#389]
im adding `:retry-handle #(do false)` to the options but the retry still happens, is it possible to disable it forever?

**Comment by dakrone** [comment]
Can you expand on where you're seeing the retry? What is it retrying after? I need to figure out where the retry is coming from in order to stop it.

**Comment by dakrone** [comment]
Closing as there has been no feedback, feel free to comment if this was closed erroneously.
