### ISSUE TITLE
decode-cookies option: working?

### ISSUE THREAD

**Issue by danielsz** [dakrone/clj-http#390]
I was hoping that setting `decode-cookies` option to `false` would get rid of the cookie-related warnings in the logs such as this.

```shell
WARN  org.apache.http.client.protocol.ResponseProcessCookies: Invalid cookie header: "set-cookie: guest_id=v1%3A150105405928877671; Expires=Fri, 26 Jul 2019 07:27:40 UTC; Path=/; Domain=.twitter.com". Invalid 'expires' attribute: Fri, 26 Jul 2019 07:27:40 UTC
```

Alas.

I know I can suppress the warning via the logging system, but am I misunderstanding that option?

**Comment by dakrone** [comment]
The `decode-cookies` option is only for making the cookies into a Clojure map in the response, I'm not sure what the option is to tell the apache client not to decode the cookie itself :( (also, sorry for the delay on this)

**Comment by dakrone** [comment]
Closing this since I think it's Apache's issue, not clj-http's, feel free to re-open though!

**Comment by zsau** [comment]
This is indeed possible via [HttpClientBuilder.disableCookieManagement](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html#disableCookieManagement()). But I believe that would need to be injected into `core/http-client`, which doesn't seem possible for a caller to do currently.

Ideally there'd be a way to arbitrarily customize the `HttpClientBuilder` used by clj-http, though I can't think of a good way to provide a hook for that.

**Comment by dakrone** [comment]
@zsau actually that gives me an idea for a way to do that, I'll experiment with it.
