### ISSUE TITLE
Requesting information from a HTTPS API

### ISSUE THREAD

**Issue by ILoveHubGit** [dakrone/clj-http#392]
I've written a small program to retrieve information from an api (https). In development this works fine. Running the Uberjar file on my development PC (Ubuntu 17.04) also works fine.
But if I start the Uberjar file on a Raspberry PI running Openmediavault I get an error "java.security.SignatureException: Signature does not match.".
I checked the certificate for the api and updated the /etc/ssl/certs on the PI, but this didn't help me.

I added the option {:insecure? true} to the get command and now it is working on the PI. 
However this is not a situation I want to put in production.

Do you have a clue on what I could do? Am I doing something wrong?

**Comment by dakrone** [comment]
It sounds like maybe your JDK may be older? I know the more recent JDKs added support for things like LetsEncrypt certificate authority and some others. Perhaps try upgrading and see if it resolves the issue?

**Comment by dakrone** [comment]
Closing as there has been no feedback, feel free to comment if this was closed erroneously.
