### ISSUE TITLE
Remove deprecated :follow-redirects options

### ISSUE THREAD

**Issue by rymndhng** [dakrone/clj-http#414]
The supported way of setting redirects is using `:redirect-strategy`. We should remove the `:follow-redirects` option and the deprecated middleware.

I think this will address the confusion around redirects and all the many options.

Done Criteria:
- [x] Updated README
- [x] Updated Changelog
- [ ] Removed :follow-redirects (boolean) option

**Comment by dakrone** [comment]
Yep, this can be done now that we have a 4.x branch :)
