### ISSUE TITLE
Consider adding probot to maintain the Repository

### ISSUE THREAD

**Issue by rymndhng** [dakrone/clj-http#415]
I'm throwing it out there. What do folks think about adding https://probot.github.io/apps/ to help manage the community. In particular, I'd be interested in trying out the following features to help maintain the repo:

- Stale: https://probot.github.io/apps/stale/
- Update Docs: https://probot.github.io/apps/update-docs/
- First Timers: https://probot.github.io/apps/first-timers/

**Comment by dakrone** [comment]
I'm +0 on it, could go either way, curious if others think it'd be helpful.

**Comment by rymndhng** [comment]
Let's leave it as it is. Keeps things simple :)
