### ISSUE TITLE
Bad redirect on asynchronous request calls neither the exception callback or the response callback

### ISSUE THREAD

**Issue by ejschoen** [dakrone/clj-http#416]
The URL below has a bad redirect.  It redirects to `https:///`.  Synchronously, this throws an exception.  Asynchronously, nothing happens.  

```
 (try
      (http/get "http://1.usa.gov/cancer/dcpc/resources/features/lungcancer/images/lung-350x361.jpg"
                {:async? true
                 :insecure? true}
                (fn [resp]
                  (println "Async response" resp))
                (fn [exc]
                  (println "Async error cb" exc)))
      (catch Throwable e
          (println "Async exception"  e)))
```

I've got code like this inside a clojure.core.async async pipeline, and the lack of a callback is causing the pipeline to block, 'cause nobody closes the pipeline stage output channel.

I guess I can make the HTTP GET call synchronous, but it really ought to work.

**Comment by dakrone** [comment]
Thanks @ejschoen, what version of clj-http are you using?

**Comment by ejschoen** [comment]
I ran into it with 3.7.0.  I did a little investigation with 4.0.0-SNAPSHOT.  If I emulate in the repl what `clj-http.core/request` does, and manually configure the Apache async client with minimal configuration settings, then the `FutureCallback` `failed` method does get invoked, and my `raise` function does get called.  However, if I use `clj-http.client/request`, and even minimally configure the middleware (`wrap-url` and `wrap-method`), then no callback.  

I was thinking the issue was with options in the `RequestConfig` or `HttpClientContext`, but haven't had time to revisit the problem.  For now, I am simply using synchronous fetches in the places where I am most apt to run into bad links.

**Comment by dakrone** [comment]
@ejschoen I finally figured out what is causing this, and I'm mulling over the best way to fix it. Basically in order to throw an exception we need to do extra checking that the URI is actually valid in the RedirectStrategy.

Before I commit to a fix, do you use a particular redirect strategy right now? (or do you just use the default)

**Comment by ejschoen** [comment]
Default.  Thanks for persevering!

Eric

**Comment by dakrone** [comment]
@ejschoen whew! this should finally be fixed now, and will be released in the next 3.x/4.x release, thanks for your patience!
