### ISSUE TITLE
Need Help on HTTP/POST of binary data.

### ISSUE THREAD

**Issue by 1v1a3x** [dakrone/clj-http#420]
Hello, 

I have an example of CURL I using for healthchek 
curl 'https://example.com/makeAction?key=Id' -H 'Connection: keep-alive' --data-binary '[object Object]' --compressed

Could you please coordinate me on how to pass the --data-binary into (client/post) ?

(client/post  "https://api.creatoriq.com/rest/user/100001334/sendInvitation?key=Id"
{
:headers {"Connection" "keep-alive"}
: ???
}
)

Thank you.

**Comment by dakrone** [comment]
Passing `--data-binary '[object Object]` should be the same as `:body "[object Object]"` in the request

**Comment by 1v1a3x** [comment]
Thank you a lot Lee.
It really works as you described.
