### ISSUE TITLE
'show-functions' name collision aws.s3 and aws.s3transfer

### ISSUE THREAD

**Issue by jrbrodie77** [dakrone/clj-http#423]
I'm trying to follow the readme using Cursive.  When I use

`(ns my.core
    (:use [amazonica.aws.s3]
             [amazonica.aws.s3transfer]))`

I get a collision between 'show-functions' functions and an error in the REPL, using Cursive/Lein.

I'm a clojure newb, but if anyone is willing to explain why this isn't or is a problem, let me know!  I did manage to make it work by replacing the :use by a :require with aliases.

**Comment by rymndhng** [comment]
Hey there. This looks like an issue that isn't related to clj-http per se. 

In general, it's preferrable to use a require syntax instead, so that the imported functions are prefixed. This way you avoid the collision. For example:

``` clj
(ns my.core
  (:require [amazonica.aws.s3 :as s3]
            [amazonica.aws.s3transfer :as s3transfer])

(s3/show-functions ..)
(s3transfer/show-functions ..)
```

**Comment by jrbrodie77** [comment]
Sorry, I posted this on the wrong project!  I was using both in my project.  I'll move it over.  The amazonica docs have an example using 'use', your suggestion does work, but I wanted to point out an error in the docs.
