### ISSUE TITLE
Socks Proxied Connection Managers seem broken

### ISSUE THREAD

**Issue by quoll** [dakrone/clj-http#425]
The modification for make-socks-proxied-conn-manager seems to have broken with commit:

[conn_mgr.clj on June 21, 2017](https://github.com/dakrone/clj-http/commit/edcd9662aeba7689aed9d134c3c84f3a309ae985#diff-284210b34a647bd6d8b1f45c2e79036a)

Previously, this function only accepted `hostname` and `port` arguments. It is now multi-arity, with the second arity accepting an `opts` argument. However, the original 2-argument arity appears to have a problem.

The 2 argument arity calls the 3 argument arity with empty `opts`. This leads the new `ssl-context` to be set to nil. This gets passed to the `SSLGenericSocketFactory` as a second argument, causing the 2-argument version of this function to be invoked. That tries to construct a `org.apache.http.conn.ssl.SSLConnectionSocketFactory` with a null context, which throws an exception. i.e. The 2 argument arity will always fail.

To duplicate the previous behavior, either the single-argument form of `SSLGenericSocketFactory` should be called when the `ssl-context` is nil, or else, the implementation of the 2 argument form of `SSLGenericSocketFactory` should set up nil contexts with `(SSLContexts/createDefault)`.

**Comment by dakrone** [comment]
I believe this was resolved in #426, so I'm closing this, let me know if this does not fix it
