### ISSUE TITLE
Async + multipart 

### ISSUE THREAD

**Issue by grinderrz** [dakrone/clj-http#431]
Combination of async + multipart results in exception:
Multipart form entity does not implement #getContent()

**Comment by grinderrz** [comment]
There is test in PR, which can be used to reproduce this bug.

**Comment by borkdude** [comment]
I'm uploading a file of 383KB and I'm seeing this exception:

org.apache.http.ContentTooLongException: Content length is too long: 383695

**Comment by fuzzyami** [comment]
we're seeing this as well. why was this closed?

**Comment by YaelKhalman** [comment]
@borkdude have you finally succeeded to overcome the "Content length is too long" issue? 
Are you using another library instead? Or fixed this one?

**Comment by borkdude** [comment]
@YaelKhalman Sorry, totally forgot what I was doing around this time. But I've also been using the aleph async client as well. Http-kit also supports async.

**Comment by YaelKhalman** [comment]
@borkdude thanks
http-kit finally worked for me

@dakrone I'm opening a separate [issue](https://github.com/dakrone/clj-http/issues/560) on async request file size limitation as the issue still exists and this one is closed
