### ISSUE TITLE
Back-porting :save-request to 3.x

### ISSUE THREAD

**Issue by rymndhng** [dakrone/clj-http#438]
I'd like to use the re-implemented :save-request feature on the 3.x branch. @dakrone , wondered what your thoughts were doing this. Alternatively, I can fork for now and keep a separate version until 4.x becomes more stable.

update: nevermind it looks like it's there, more so releasing `3.8.x`

**Comment by dakrone** [comment]
I can definitely do a release. I think 3.x definitely has had enough changes to warrant one. Give me a few and I'll release 3.8.0

**Comment by dakrone** [comment]
Done! 3.8.0 has been released.

**Comment by rymndhng** [comment]
Thank you! :D
