### ISSUE TITLE
Investigate reusing HttpClient between requests

### ISSUE THREAD

**Issue by dakrone** [dakrone/clj-http#441]
It may not need to be created every time, instead, it could be reused.

Related to #371

**Comment by dakrone** [comment]
@serioga please check out https://github.com/dakrone/clj-http/commit/98885eb3bd9c54949f97231d020df2af15036d62 and let me know if that works for you!

**Comment by serioga** [comment]
@dakrone do you want me to check before releasing or clojars or I can wait for release?
The commit looks promising :-)

**Comment by dakrone** [comment]
@serioga if the commit looks like it will provide what you need that's good enough for me, it'll go out in the 3.9.0 release. I just released 3.8.0 though, so it may be a little bit before another release

**Comment by serioga** [comment]
@dakrone architecturally it looks perfect 👍

**Comment by dakrone** [comment]
Excellent, it'll be in the next release then!

**Comment by aleksandersumowski** [comment]
Any timeline for 3.9 release?

I'd like to instrument my clj-http calls with X-Ray and I understand this feature would allow me to pass TracedHttpClient[1] to clj-http.


[1] https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-apache-http/src/main/java/com/amazonaws/xray/proxies/apache/http/TracedHttpClient.java

**Comment by dakrone** [comment]
Hi @aleksandersumowski I would expect a 3.9 release sometime in the next week or so, would that work for you?

**Comment by aleksandersumowski** [comment]
yes, that would work. thanks a lot for great work!

**Comment by serioga** [comment]
Hello @dakrone 

Following [example](https://github.com/dakrone/clj-http#re-using-httpclient-between-requests) looks a little bit confusing about `:connection-manager` key usage:

```clojure
;; You can also build your own, using clj-http's helper or manually building it:
(let [cm (conn/make-reusable-conn-manager {})
      hclient (core/build-http-client {} cm "https://example.com" false)]
  (client/get "http://example.com/1"
              {:connection-manager cm :http-client hclient})
  (client/get "http://example.com/2"
              {:connection-manager cm :http-client hclient})
  (client/get "http://example.com/3"
              {:connection-manager cm :http-client hclient}))
```

a. Should we really specify `:connection-manager` after using it in `core/build-http-client`?

b. What happened if we use one conn-manager instance in `core/build-http-client` but another one as `:connection-manager` key?

**Comment by serioga** [comment]
ah, and parameter order is wrong in `(core/build-http-client {} cm "https://example.com" false)`
