### ISSUE TITLE
CacheConfig option for HttpClient

### ISSUE THREAD

**Issue by RokLenarcic** [dakrone/clj-http#445]
Currently the client doesn't support setting CacheConfig, which would enable the client to honor the caching headers are per RFC. All that is really needed is a change to `build-http-client` to read `:cache-config` request option for a possible `CacheConfig` object.

Example use from HttpComponents:

```
CacheConfig cacheConfig = CacheConfig.custom()
        .setMaxCacheEntries(1000)
        .setMaxObjectSize(8192)
        .build();
RequestConfig requestConfig = RequestConfig.custom()
        .setConnectTimeout(30000)
        .setSocketTimeout(30000)
        .build();
CloseableHttpClient cachingClient = CachingHttpClients.custom()
        .setCacheConfig(cacheConfig)
        .setDefaultRequestConfig(requestConfig)
        .build();

```

**Comment by dakrone** [comment]
Sounds good, I'll add this

**Comment by dakrone** [comment]
@RokLenarcic I've pushed a commit that adds this! can you take a look (at the commit or master branch) and let me know what you think?

**Comment by RokLenarcic** [comment]
Looks great!
