### ISSUE TITLE
add an option reuse-client?

### ISSUE THREAD

**Issue by jiacai2050** [dakrone/clj-http#452]
For 3.9.0, all reponses contains an key `:http-client` for reuse, that's a [good suggestion](https://github.com/dakrone/clj-http/commit/98885eb3bd9c54949f97231d020df2af15036d62), unfortunately this break to use those responses as rpc result.
For my case, it throw `No reader function for tag object`, the rpc lib I use use `clojure.edn/read-string` to deserialize results , so I would like to add `reuse-client?` option and default to `true`, If this makes sense to mantainers, I would like to send a PR.

**Comment by dakrone** [comment]
Can you explain what you mean by "rpc result"? I'm a little confused by what you mean

**Comment by jiacai2050** [comment]
Oh, it's `rpc's response`.

**Comment by jiacai2050** [comment]
In a RPC environment, parameters and response must be serialized in order for a client to call a remote function,  the RPC library I use use `clojure.edn/read-string` to deserialize response, and `edn/read-string` can't read something like 

`:http-client #object[org.apache.http.impl.client.InternalHttpClient 0x10fe4f0e "org.apache.http.impl.client.InternalHttpClient@10fe4f0e"]` 

it will throw Exception `No reader function for tag object`, so I want to add `reuse-client?` option to determine if response of clj-http should contain `:http-client`.

Make sense?

**Comment by LucianaMarques** [comment]
Hi there.

Was this ever solved? I ran into a similar issue.

Thanks!

**Comment by jiacai2050** [comment]
@LucianaMarques I think no progress has been made. It's better you select specific keys out of clj-http's response before reuse.
