### ISSUE TITLE
resources/log4j2.properties overrides other log4j2 config files

### ISSUE THREAD

**Issue by jarohen** [dakrone/clj-http#455]
Hi there - adding the example log4j2.properties file to your resources directory means it takes preference over the log4j2.json file that I have on my classpath. If it's an example file, could it be renamed to example-log4j2.properties, or similar?

Workaround is to explicitly configure the `log4j.configurationFile` JVM property (which wasn't necessary before this clj-http update)

Log4j2's configuration preference order is at https://logging.apache.org/log4j/2.x/manual/configuration.html

Cheers!

James

**Comment by delitescere** [comment]
This file should be in examples only.

**Comment by dakrone** [comment]
I've renamed the file for now, thanks for bringing it to my attention and for the workaround
