### ISSUE TITLE
query-params doesn't encode params?

### ISSUE THREAD

**Issue by rainmote** [dakrone/clj-http#468]
I tried to wrap gerrit rest api with clj-http, but I encountered an access error after encoding the url parameter. eg:
https://www.gerritcodereview.com/rest-api-changes.html#query-changes

request:
` GET /changes/?q=status:open+is:watched&n=2 HTTP/1.0`

use clj-http:
`status:open+is:watched` is encoded as `status%3aopen%2bis%3awatched`
and request error.

**Comment by dakrone** [comment]
Hi @rainmote can you share the clojure code you use to send the request?

**Comment by rainmote** [comment]
@dakrone 

```
(defn default-params []
  {:url (-> env :gerrit :url)
   ;:proxy-host "127.0.0.1"
   ;:proxy-port 8080
   :digest-auth [(-> env :gerrit :user)
                 (-> env :gerrit :passwd)]
   })

(defn request [params]
  (-> (default-params)
      (merge ,,, params)
      (assoc ,,, :url (-> env :gerrit :url
                          (str ,,, "/a/" (:path params))
                          (clojure.string/replace ,,, #"([^:])//+" "$1/")))
      http/request
      process-resp))

(defn construct-query-params
  " {:a 1 :b 2} => a:1+b:2"
  [params]
  (->> params
       (map #(str (-> % first name) ":" (second %)) ,,,)
       (clojure.string/join "+" ,,,)))

(defn query-changes
  [{:keys [project branch status]
    :or {project "myproject"
         status "merged"}
    :as params}]
  (->> {:method :get
        :query-params {:q (construct-query-params params)}}
       request))
```

the http/request is wrap clj-http
```
;; (:require [clj-http.client :as client])

(def default-params
  {:throw-exceptions false
   :retry-handler retry-handler
   })

(defn construct-headers [header]
  (-> default-headers
      (merge , (or header {}))))

(defn construct-params
  [params]
  (-> default-params
      (merge ,,, params)
      (assoc ,,, :headers (construct-headers (:headers params)))))

(defn request [params]
  (->> (construct-params params)
       client/request))
```
thanks.

**Comment by dakrone** [comment]
Hi @rainmote 
This is something you should let clj-http handle encoding of, for example:

```clj
(get "http://localhost:9000" {:query-params {"q" "status:open is:watched" "n" 2}})
```

Returns an encoded query string of:

```
GET /?q=status%3Aopen+is%3Awatched&n=2 HTTP/1.1
```

Which is correctly decoded by HTTP servers:

```json
~ λ curl "httpbin.org/anything?q=status%3Aopen+is%3Awatched&n=2"
{
  "args": {
    "n": "2", 
    "q": "status:open is:watched"
  }, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Connection": "close", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.61.1"
  }, 
  "json": null, 
  "method": "GET", 
  "origin": "174.16.228.149", 
  "url": "http://httpbin.org/anything?q=status%3Aopen+is%3Awatched&n=2"
}
```

Instead of doing the query string construction on your own

**Comment by rainmote** [comment]
@dakrone thank you very much.

Your reply reminded me, spaces in url will be escaped. I found https://www.w3.org/TR/2003/PR-xforms-20030801/slice11.html#serialize-urlencode

> The encoding of EltName and value are as follows: space characters are replaced by +, and then non-ASCII and reserved characters (as defined by [RFC 2396] as amended by subsequent documents in the IETF track) are escaped by replacing the character with one or more octets of the UTF-8 representation of the character, with each octet in turn replaced by %HH, where HH represents the uppercase hexadecimal notation for the octet value and % is a literal character. Line breaks are represented as "CR LF" pairs (i.e., %0D%0A).

thanks again ^_^
