### ISSUE TITLE
Do not specify charset for multipart requests

### ISSUE THREAD

**Issue by alextrofymenko** [dakrone/clj-http#472]
This currently stops IIS correctly interpreting the boundary, preventing any form fields from being populated correctly. As far as I can tell from RFC spec it doesn't apply to multipart content type anyway, and each part can have it's own content type with charset set (and will definitely have it in strict mode).

Header with charset: 
```
Content-Type: "multipart/form-data; boundary=6jf2VVQVqEg7h0W6wwvwA8A58_j0TMsYKB8zWc3; charset=UTF-8"
```

Header without charset: 
```
Content-Type: "multipart/form-data; boundary=6jf2VVQVqEg7h0W6wwvwA8A58_j0TMsYKB8zWc3"
```

Removing the following line fixes the problem: https://github.com/dakrone/clj-http/blob/c9d36252396a3f514eef757ef3e52d515f04df7a/src/clj_http/multipart.clj#L134

**Comment by conao3** [comment]
#473 was merged, so this issue is completed?

**Comment by alextrofymenko** [comment]
I believe so, I am closing this issue as completed
