### ISSUE TITLE
No warning when using :as :json without the cheshire dependency

### ISSUE THREAD

**Issue by bfontaine** [dakrone/clj-http#479]
I got the same isse as #281 and #282 where I used `{:as :json}` but didn’t get a map because I was missing the `cheshire` dependency.

Do you think it’d be a good idea to raise an exception when someone uses `:as :json` and friends without the associated dependency?

**Comment by dakrone** [comment]
@bfontaine yeah, it'd probably be nice if it threw an error rather than silently failing
