### ISSUE TITLE
reusable vs. reuseable

### ISSUE THREAD

**Issue by ptuckey** [dakrone/clj-http#482]
The sync connection manager spells "make-reusable" differently than the async version:
[make-reusable-conn-manager](https://github.com/dakrone/clj-http/blob/3887459cbc9fca8af04a807cfb4cf65ca6b4ecdd/src/clj_http/conn_mgr.clj#L323)
[make-reuseable-async-conn-manager](https://github.com/dakrone/clj-http/blob/3887459cbc9fca8af04a807cfb4cf65ca6b4ecdd/src/clj_http/conn_mgr.clj#L388)

This is a minor annoyance, but "gotcha'd" me when switching between them, for testing purposes.

If this is worth addressing, perhaps a wrapping function **make-reusable-async-conn-manager**?

Thank you for this terrific library, and thanks for your consideration!

**Comment by dakrone** [comment]
Whoops that's a really good catch, I totally missed that I named them incorrectly.

I think a wrapping function would be useful, would you be interested in opening a PR for it?
