### ISSUE TITLE
Add a 'complete' example of get function on the documentation

### ISSUE THREAD

**Issue by cybersapiens97** [dakrone/clj-http#485]
It took me an entire hour to figure out that the get function and it's map options works like this:
 `(client/get URL
                   {:query-params ...
                    :headers ....
                    :other-options ....})`

i think it would be nice to add this on the documentation, since there we have only examples using single options, and it was a little hard to me to figure out that it was a map of options, instead of multiple maps of options.

**Comment by dakrone** [comment]
Sure that sounds good, do you want to add an example to the readme @cybersapiens97?

**Comment by rymndhng** [comment]
@cybersapiens97 Can you take a look at the PR I've linked to see if it addresses your issue?
