### ISSUE TITLE
Usage from inside Kubernetes

### ISSUE THREAD

**Issue by jwhitlark** [dakrone/clj-http#486]
It took me quite some time to figure out how to call the Kubernetes api from inside a pod, with the custom certs, etc.

I wrote up a quick gist, do you think it's worth adding to the wiki or docs?

https://gist.github.com/jwhitlark/8e42baadbd86147547d1cdb08c81191c

**Comment by dakrone** [comment]
Looks useful to me, do you want to open a PR adding it in a file to the `examples` directory?
