### ISSUE TITLE
Feature request: Add {:as :reader} response-body coercion

### ISSUE THREAD

**Issue by benjamin-bader** [dakrone/clj-http#502]
It would be handy to be able to receive responses as instances of BufferedReader.  We could of course do this ourselves, but seeing as how there is already logic in the client for handling response charsets, it would seem simple to add to clj-http.

What do you think?  I'm happy to put together a PR if you decide this is worth doing.

**Comment by dakrone** [comment]
@benjamin-bader that sounds reasonable enough, if you want to open a PR that would be great.

**Comment by benjamin-bader** [comment]
Cool, glad to hear it, I'll see what I can do.

Should I be working out of `master` or `3.x`?  I'd assume `master` but `3.x` appears to be more-recently-active.

**Comment by dakrone** [comment]
`3.x`, this is the most maintained and changes that are merged to it are forward-ported where needed.
