### ISSUE TITLE
Records not supported for form-params in JSON?

### ISSUE THREAD

**Issue by kendagriff** [dakrone/clj-http#508]
We recently upgraded to 3.10.0 from 2.x.x and found that our form-params were coming out like this in a request:

```JSON
{
  "batch": "sf.sponsors.easypost.Batch@a2c24201",
  "format": "json",
  "controller": "batches",
  "action": "create"
}
```

Note the `batch` key is a record, and wasn't treated like a map. Is that intentional? Are records not supported?

**Comment by rymndhng** [comment]
I believe 3.x has more control over how form-params encodes nested structures. You will need to add `:flatten-nested-form-params true` to transform nested structures properly. See https://github.com/dakrone/clj-http#post

I wrote a small test to show this is the case

``` clojure
(defn write-to-stdout [req]
  (let [baos (ByteArrayOutputStream.)]
    (.writeTo baos (:body req))
    (println (.toString baos))))

;; no options specified
(with-redefs [core/request write-to-stdout]
  (post "http://www.fool.com" {:form-params {:batch (Batch. "foo" "bar" "baz")}}))
;; => batch=clj_http.client.Batch%40b66d38dd

;; set :flatten-nested-form-params true
(with-redefs [core/request write-to-stdout]
  (post "http://www.fool.com" {:form-params {:batch (Batch. "foo" "bar" "baz")}
                               :flatten-nested-form-params true}) )
;; => batch%5Bfoo%5D=foo&batch%5Bbar%5D=bar&batch%5Bbaz%5D=baz
```

**Comment by kendagriff** [comment]
I see. Does `{:content-type :json}` make `:flatten-nested-form-params` unnecessary?

**Comment by rymndhng** [comment]
If your server supports JSON, then I would recommend specifying JSON, since it's much better for reliably parsing structured data.

And you are correct that if you encode the data as JSON , you do not need `:flatten-nested-form-params`.

**Comment by kendagriff** [comment]
Perfect, that helps a lot!
