### ISSUE TITLE
Is there a way to check if a cookie has the flag HttpOnly?

### ISSUE THREAD

**Issue by mourjo** [dakrone/clj-http#513]
For example, the cookie in this test file has the attribute `HttpOnly`
https://github.com/dakrone/clj-http/blob/070e34a783e4c477bdb9bec3010b7b135ce22de8/test/clj_http/test/core_test.clj#L135 

I was wondering if there is a way to extract it when I pass a `CookieStore` to requests. This is not returned by default when I use `get-cookies`, I didn't find a way this can be done in `ClientCookie` either, wondering if I am missing something.

**Comment by rdivyanshu** [comment]
I don't know if it solves your problem but to check cookie has attribute HttpOnly, you need to call 
`(.containsAttribute ^ClientCookie cookie "httponly")`

**Comment by mourjo** [comment]
@rdivyanshu yes it does! Thanks a lot!
