### ISSUE TITLE
Performance warnings with `*warn-on-reflection*`

### ISSUE THREAD

**Issue by jsyrjala** [dakrone/clj-http#528]
`[clj-http "3.10.0"]` shows these warnings with `*warn-on-reflection* true`

```
Performance warning, clj_http/util.clj:75:11 - case has int tests, but tested expression is not primitive.
Performance warning, clj_http/util.clj:89:11 - case has int tests, but tested expression is not primitive.
Performance warning, clj_http/client.clj:463:11 - case has int tests, but tested expression is not primitive.
```

Offending places
- util.clj line 75: https://github.com/dakrone/clj-http/blob/3.x/src/clj_http/util.clj#L75
- util.clj line 89: https://github.com/dakrone/clj-http/blob/3.x/src/clj_http/util.clj#L89
- client.clj line 463:  https://github.com/dakrone/clj-http/blob/3.x/src/clj_http/client.clj#L463

**Comment by frenchy64** [comment]
I believe the client.clj performance warning has been reintroduced after this commit (link to responsible line) https://github.com/dakrone/clj-http/commit/5154fcc6b24a9ce4bbff6ba45c971c19976491a3#diff-7859f5b782fecf9ed95b6d40e8567053R453

I can prepare another patch.

In the future it might help to enable `*warn-on-reflection*` in the build.
