### ISSUE TITLE
Example code in README for manual HttpClient build doesn't work

### ISSUE THREAD

**Issue by wmatson** [dakrone/clj-http#530]
```Clojure
;; You can also build your own, using clj-http's helper or manually building it:
(let [cm (conn/make-reusable-conn-manager {})
      hclient (core/build-http-client {} cm "https://example.com" false)]
  (client/get "http://example.com/1"
              {:connection-manager cm :http-client hclient})
  (client/get "http://example.com/2"
              {:connection-manager cm :http-client hclient})
  (client/get "http://example.com/3"
              {:connection-manager cm :http-client hclient}))
```

`core/build-http-client` takes a boolean for `caching?` before the connection-manager and the url supplied isn't necessary.

**Comment by wmatson** [comment]
I can probably make a PR to fix it, I just need to find the time. Is it required to attach the connection-manager when attaching the http-client?

**Comment by dakrone** [comment]
@wmatson a PR for this would be great. I'm not sure what the second part of your question refers to, can you clarify?

**Comment by wmatson** [comment]
```clojure
(let [cm (conn/make-reusable-conn-manager {})
      hclient (core/build-http-client {} false cm)]
  (client/get "http://example.com/1" {:http-client hclient}))
```
This "works", but [the documentation](https://github.com/dakrone/clj-http#re-using-httpclient-between-requests) implies that it shouldn't:
> Note that in order to reuse the client a connection manager must be used.

**Comment by wmatson** [comment]
@dakrone I looked through the source and found that it's "harmless" to not supply the connection manager as specified in my previous comment's code snippet, although it does cause an unused connection manager to be created and shutdown.

Although it's impossible to get the connection manager from the HttpClient with the non-deprecated HttpClient API, it might be possible to not create one on `request` invocation if `:http-client` is supplied. Would you like me to add that to this PR or create a separate issue/PR for it?
