### ISSUE TITLE
Debug output does not keep output together when running in multiple threads

### ISSUE THREAD

**Issue by ilmoraunio** [dakrone/clj-http#536]
We noticed that `clj-http.core/print-debug!` does not keep output together when running in multiple threads.

You should be able to replicate the problem with this:

```clojure
(dotimes [_ 10]
  (future (clj-http.client/get "https://www.google.fi" {:debug true})))
```

Wrapping the print logic with `(println (with-out-str …))` seems to solve the issue, but I'm a bit worried about it being a bit too dirty. Is this approach PR-worthy or should I give it a rethink?

```clojure
(defn- print-debug!
  "Print out debugging information to *out* for a given request."
  [{:keys [debug-body body] :as req} http-req]
  (println (with-out-str
             (println "Request:" (type body))
             (clojure.pprint/pprint
                           (assoc req
                                  :body (if (opt req :debug-body)
                                          (cond
                                            (isa? (type body) String)
                                            body

                                            (isa? (type body) HttpEntity)
                                            (let [baos (ByteArrayOutputStream.)]
                                              (.writeTo ^HttpEntity body baos)
                                              (.toString baos "UTF-8"))

                                            :else nil)
                                          (if (isa? (type body) String)
                                            (format "... %s bytes ..."
                                                    (count body))
                                            (and body (bean body))))
                                  :body-type (type body)))
                         (println "HttpRequest:")
                         (clojure.pprint/pprint (bean http-req)))))
```

**Comment by rymndhng** [comment]
This seems like a reasonable improvement 👍 (note: I am an occasional contributor, and not the maintainer)

I don't think it's that dirty considering that I would have suggested as an alternative to create a `java.io.StringWriter` and explicitly pas it to all the print functions. `with-out-str` does the same thing :)

**Comment by dakrone** [comment]
@rymndhng I find myself pretty short on time these days, so please do feel free to take on as much reviewing/merging/etc as you'd like, I appreciate the help!

@ilmoraunio your solution seems like a reasonable one to me, feel free to open a PR

**Comment by ilmoraunio** [comment]
Thanks for taking care of this @rymndhng 👍
