### ISSUE TITLE
How can I set the encoding-pattern like slurp?

### ISSUE THREAD

**Issue by temco** [dakrone/clj-http#586]
With slurp, I could set the encoding-pattern of the target page, like `(slurp "https://xxx.com" :encoding "utf-8")`.
How can I do this with clj-http? Thanks a lot.

**Comment by rymndhng** [comment]
See https://github.com/dakrone/clj-http#output-coercion.

There are some options there for coercing the output encoding.

**Comment by temco** [comment]
> See https://github.com/dakrone/clj-http#output-coercion.
> 
> There are some options there for coercing the output encoding.

thanks
