### ISSUE TITLE
Switch to built in http client (introduced in java 11)

### ISSUE THREAD

**Issue by kirillsalykin** [dakrone/clj-http#602]
It seems make sense to use built in http client cause it will reduce deps and built in machinery better known/used.

what do you think?

**Comment by dakrone** [comment]
It sounds like you might want to check out https://github.com/hiredman/clj-http-lite (and its associated forks), that would be a better place to switch to this.

**Comment by oliyh** [comment]
See also https://github.com/gnarroway/hato

**Comment by kirillsalykin** [comment]
Makes sense, thanks!
