### ISSUE TITLE
Handling of private proxies 

### ISSUE THREAD

**Issue by zackteo** [dakrone/clj-http#616]
I have a private proxy like the following example from https://superuser.com/questions/1262861/what-is-a-proxy-username-and-password
`http://dshowerhandle:SuperSecretPassword@us.paidproxy.com`

**Am I right to say that private proxies are currently unsupported in clj-http?**

Currently, when I try to do a request with 
```clojure
{:proxy-host "dshowerhandle:SuperSecretPassword@us.paidproxy.com"
 :proxy-port 8080}
```
I will get the following error
```
Unhandled java.net.UnknownHostException
   http://dshowerhandle:SuperSecretPassword@us.paidproxy.com: invalid IPv6 address
```
I know that this the proxy works as I can make a successful request with curl

**Comment by dakrone** [comment]
Something to try, have you tried specifying the proxy host using the java system property `http.proxyHost` and see if that one supports the authenticated proxy?

**Comment by zackteo** [comment]
Hi @dakrone thanks for your quick response. I discovered that proxies with passwords are actually supported: https://github.com/dakrone/clj-http/blob/5a5288319abab50141b8785625feca8de5a11dfc/src/clj_http/core.clj#L557

Was just previously confused since it wasn't mentioned in the README: https://github.com/dakrone/clj-http#proxies
